.github/CONTRIBUTING.md, DEVELOPERS.md, Dockerfile, LICENSE, README.md, code_of_conduct.md, codecov.yml
first work on documenting this monstrosity.
closes #92
=> docs: adding intial documentation for release

core/datasets.go, core/datasets_test.go, repo/test/test_repo.go, vendor/github.com/qri-io/dataset/validate/csv.go, vendor/github.com/qri-io/dataset/validate/csv_test.go, vendor/github.com/qri-io/dataset/validate/data.go, vendor/github.com/qri-io/dataset/validate/data_test.go, vendor/github.com/qri-io/dataset/validate/testdata.go, vendor/vendor.json
- NOTE: will need to be merged alongside a merge of datasets/detect/determineFields.go due to updated csvReader config
closes #139
=> test(csvValidation): added additional csv validation and updated tests

core/params_test.go, core/profile_test.go, core/queries.go, core/queries_test.go
=> test(core): added minimal tests for core.profile and core.requests

core/datasets.go, core/datasets_test.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/fs/namestore.go, repo/mem_namestore.go, repo/repo.go, repo/test/test.go, repo/test/test_namespace.go
=> test(repo.Namespace): added repo.Namespace tests

core/queries.go, repo/graph.go, vendor/github.com/qri-io/dataset_sql/exec_test.go, vendor/github.com/qri-io/dataset_sql/prepare.go, vendor/github.com/qri-io/dataset_sql/prepare_test.go, vendor/vendor.json
=>  feat(core.QueryRequests.Query): check for previously exectued queries

api/handlers/datasets.go, api/handlers/queries.go, api/server.go, cmd/add.go, cmd/rename.go, core/datasets.go, core/datasets_test.go, core/queries.go, core/queries_test.go, repo/graph.go, repo/graph_test.go
add suport for getting the queries that list a dataset as a resource
=>  feat(core.QueryRequests.DatasetQueries): first implementation

api/handlers/context.go, api/handlers/context_test.go, api/handlers/datasets.go, api/handlers/root.go, api/middleware.go, api/server.go, api/server_test.go, core/datasets.go
=> WIP refactor(api, list, dataset info): add `/list/` and `/[peername]/[datasetname]` with tests and test stubs

Dockerfile, Makefile, README.md, p2p/bootstrap.go
also updated readme to add build instructions.
closes #27.
=> feat(makefile): added make build command

api/handlers/datasets.go, api/server.go, api/server_test.go
=> fix(api, save): fix bugs to allow save API endpoint to work

api/handlers/history.go, api/server.go, api/server_test.go, cmd/log.go, cmd/repo.go, core/history.go, core/history_test.go, p2p/datasets.go, p2p/handlers.go, p2p/message.go
=> feat(log,history): get a peer's dataset log

cmd/export.go
single line addition I think gets almost everything we wanted working
closes #212 
closes #213
=> feat(export): export to zip file and export directory using dataset name

api/handlers/datasets.go, api/server.go, api/server_test.go, cmd/add.go, core/datasets.go, p2p/datasets.go, p2p/handlers.go
closes #229 
closes #228 
closes #242 
closes #245 
closes #248
=> fix(add): fill out add command and api add endpoint

cmd/version.go
=> fix(cmd.version): fix incorrect version number

cmd/export.go
=> fix(cmd.Export): fixed the ordering of path and namespace

core/history_test.go, core/profile.go, repo/ref.go, repo/ref_test.go
=> refactor(ParseDatasetRef): ParseDatasetRef can now takes more flexible string input

api/datasets.go, api/server_test.go, api/testdata/addResponsePrivate.json, cmd/add.go, core/datasets.go
This private flag is just a stand in for now. If the flag is true,
return an error that refers the user to
https://github.com/qri-io/qri/issues/291 for updates.
Closes #291
=> feat(private flag): add private flag to cli and api add

api/peers.go, api/server.go, api/server_test.go, core/datasets.go, core/peers.go, repo/fs/peer_store.go, repo/fs/refstore.go
fixes a few quick errors that have immediately cropped up from our recent changes to DatasetRef
closes #223.
=> fix(DatasetRef): fixes to datasetRef handling, add back connect endpoint

api/datasets.go, core/datasets.go
=> fix(structuredData): data should return DataPath not dataset Path

README.md, troubleshooting.md
Added troubleshooting.md and linked to this document in README.md which grow out of https://github.com/qri-io/qri/issues/235.
=> Added troubleshooting.md and updated README.md to link to it

api/config.go, api/datasets.go, api/middleware.go, api/peers.go, api/profile.go, api/server.go, api/server_test.go, cmd/connect.go
closes #312 
Additionally:
* adds tests for read-only server
=> feat(read-only): add read-only mode to qri server

api/server.go, cmd/config.go, cmd/connect.go, cmd/repo.go, cmd/setup.go, config/api.go, config/config.go, config/config_test.go, config/profile.go, config/profile_test.go, config/rpc.go, config/webapp.go, repo/profile/type.go
changes to config introduced a number of problems that need addressing. Namely profile mismatches between fsrepo & the config profile storage, port mismatches, a few default configuration errors, and some missing / bad error reporting around configuration loading.
closes #328, closes #329
=> fix(config): fix issues created by config overhaul

api/transports.go, cmd/connect.go
=> refactor(connect flags): add disable flags for api, rpc, and port

repo/graph.go
follow up to qri-io/dataset#111
=> refactor(repo): remove references to Abstract dataset structs

api/server.go, cmd/setup.go, config/api.go, config/api_test.go, config/cli.go, config/cli_test.go, config/config.go, config/config_test.go, config/logging.go, config/logging_test.go, config/p2p.go, config/p2p_test.go, config/profile.go, config/profile_test.go, config/readme.md, config/repo.go, config/repo_test.go, config/rpc.go, config/rpc_test.go, config/store.go, config/store_test.go, config/webapp.go, config/webapp_test.go, p2p/node.go, repo/fs/fs_test.go
=> feat(config): validation and documentation

api/webapp.go
guys I fuxed up. this un-fuxes
=> fix(webapp): replaced hardcoded entryupintupdateaddress

cmd/cmd_test.go, config/config.go
=> fix(config): `qri config set` on an int field does not actually update

Makefile, cmd/cmd_test.go, cmd/connect.go, cmd/connect_test.go, cmd/setup.go, core/setup.go
We should wait for `https://registry.qri.io` before merging this.
=> feat(registry): Integrate Registries into codebase

core/profile.go, core/profile_test.go
testcase for core.SaveProfile, specifically, the assumptions it makes and idiosyncrasies of how it
currently works.
=> test(core.Profile): testcase for SaveProfile

repo/ref.go
Depends upon https://github.com/qri-io/dataset/pull/118
=> refactor(CodingPattern): rename usage of CodingDataset to DatasetPod

cmd/remove.go, cmd/repo.go, core/datasets.go, repo/actions/dataset.go, repo/fs/fs.go
need tests for this, but this cleans up recently-committed code to work in production
=> fix(registry): make registry post & deletes actually work

cmd/add.go, cmd/print.go, cmd/print_test.go, cmd/root.go, core/datasets.go
=> fix(cmd): changes to add, diff, and global config flag

cmd/add.go, cmd/diff.go, cmd/remove.go, cmd/rename.go, cmd/save.go, cmd/validate.go
=> docs(cmd): add examples and fix docs on help page for CLI commands

repo/actions/dataset.go, repo/actions/transform.go
Enable behavior in https://github.com/qri-io/skytf/pull/1.
=> feat(skylark): Pass previous dataset body to skylark for updates

cmd/export.go
=> refactor(cmd/export): `--blank` flag returns dataset.yaml with `viz` instructions

lib/datasets.go
Fixed the command-line version of #509.
=> fix(get): Can get another user's repo, as long as node is connected.

actions/dataset.go, actions/setup.go, actions/setup_test.go, actions/viz.go, cmd/setup.go, lib/setup.go
Closes #538. This was creating a "render" tab on the frontend when one really shouldn't be there, fixed here.
Also added a 'none' option b/c currently our registry is dead & without it you can't create a repo.
=> fix(CreateDataset): remove transform creating default viz

Makefile
License: MIT
Signed-off-by: Adrian Lanzafame <adrianlanzafame92@gmail.com>
=> remove extra double quote

README.md
=> docs(readme): adjust building from source docs based on issue #485

actions/transform.go, base/dataset.go
Rename downloadPath to downloadURL, update parameter to ExecFile.
=> fix(qri): Fix usage of dataset and startf

actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, actions/registry_test.go, api/datasets.go, base/dataset.go, base/dataset_prepare.go, base/viz.go, base/viz_test.go, cmd/print.go, cmd/save.go, cmd/update.go, lib/datasets.go, lib/lib_test.go, p2p/p2p.go
=> fix(save): move secret passing out-of-band, fix updates to viz

README.md
=> docs(fix): Adjust Contributing links in README.md

actions/registry.go, api/api_test.go, base/ref.go, cmd/cmd_test.go, cmd/publish.go, cmd/registry.go, cmd/save_test.go, lib/datasets.go, lib/registry.go
=> feat(cmd registry pin): add registry pin commands

actions/actions.go, api/datasets.go, repo/ref.go
- api publish endpoint needs to check if the dataset should or should not be pinned
- CanonicalizeDatasetRef needs to pass over the Published status of the on file dataset ref
=> fix(publish):  api publish endpoint and CanonicalizeDatasetRef fix

base/base.go, cmd/generate/generate.go, config/test/test_peers.go, docs/docs.go, lib/test/test_crypto_generator.go, main.go, p2p/test/p2ptest.go, repo/fs/fs.go, repo/profile/profile.go, repo/search/search.go
starting into a documentation cleanup. This should complete the overview of qri at https://godoc.org/github.com/qri-io/qri
=> docs: update package definition documentation

base/dataset_prepare.go, base/dataset_prepare_test.go
When a dataset is created, but doesn't have a Schema or a FormatConfig, attempt to derive these by guessing. We're already doing this for the Structure field, so this change is just expanding it to more fields.
=> fix(save): Infer more values, such as Schema, when appropriate

cmd/list.go
I often find myself typing `qri list me/my_dataset` when I should be using `qri get me/my_dataset`. Currently this is an error, because `list` expects its parameter to be only a peername (whose datasets to list), but we can do better. Instead, split the parameter into peername and a dataset name to be
used like a filter over the list results.
=> fix(list): Improve usability of `list` command

actions/list_datasets.go, actions/list_datasets_test.go, api/registry_test.go, base/dataset.go, base/dataset_test.go, cmd/list.go, cmd/print.go, lib/datasets.go, lib/params.go, p2p/datasets.go
Depends upon https://github.com/qri-io/dataset/pull/177.
=> fix(list): Flag --num-versions shows number of versions of each dataset

p2p/node.go
fixes broken build on head/master
=> fix(p2p): pass missing context to ipfsfs.GoOnline

cmd/diff.go, cmd/print.go
closes #771. 
I wanted to solve this problem the "right" way, by making sure we're always writing ANSI codes that we know will print. After some digging, this turns out to be a _way_ bigger problem than I expected, and the easier answer is to avoid using colors like `FgWhite` or `FgBlack`. Thankfully there are only a few places in our codebase that use these, and one of them was dead code. 
Here's some of the places this took me for when we end up back here in six months:
* https://github.com/twilio/twilio-cli/issues/7
* https://github.com/chalk/chalk/issues/102
* https://stackoverflow.com/questions/2507337/is-there-a-way-to-determine-a-terminals-background-color
* https://bugzilla.gnome.org/show_bug.cgi?id=733423
Neovim has a funny way of handling this: …
=> fix(cmd): don't use FgWhite, breaks light-colored termimals

Makefile, actions/remote_test.go, api/api.go, api/datasets.go, api/log.go, api/middleware.go, api/peers.go, api/profile.go, api/registry.go, api/remote.go, api/render.go, api/root.go, api/search.go, api/update.go, cmd/get.go, cmd/list.go, cmd/log.go, cmd/peers.go, cmd/search.go, cmd/update.go, lib/params.go, update/cron/http.go
sadly we're going to be shuttering some code over at data together. I'm bringing this package
into Qri so we can maintain it. Needs to be a separate repo b/c registry relies on this package as well. Sorry @dustmop, the repo count grows 😭
=> refactor(apiutil): switch datatogether apiutil to qri-io/apiutil

api/api.go, api/fsi.go, base/dataset.go, cmd/init.go, fsi/body.go, fsi/fsi.go, fsi/fsi_test.go, fsi/init.go, fsi/link.go, fsi/mapping.go, lib/datasets.go, lib/fsi.go
These methods fetch & parse the _current directory dataset_, which is not yet versioned
=> feat(api): methods for reading & saving FSI datasets via API

lib/profile.go
=> fix(lib): profileMethods need to persist their changes

api/datasets.go
desktop needs this to like, work.
=> fix(api): body requests honor full references

api/api.go, api/fsi.go, api/fsi_test.go, cmd/fsi_integration_test.go, cmd/restore.go, fsi/mapping.go, lib/fsi.go
Use restore like:
```
curl -X POST -d "component=body" localhost:2503/restore/peername/ds_name
```
closes #876
=> feat(restore): Add api for restore. Test for checkout and restore apis.

api/registry.go, cmd/factory.go, cmd/factory_test.go, cmd/qri.go, cmd/registry.go, lib/config.go, lib/lib.go, lib/registry.go, registry/profile.go, registry/regserver/handlers/profile.go, repo/repo.go
=> refactor(registry): sync local profile to registry response on signup/prove

lib/config.go, lib/profile.go, lib/registry.go, registry/profile.go, registry/regclient/profile.go
=> fix(regclient.Profile): Profile struct has field formatting details when marshalling to json

lib/lib.go
set registry.location to "mock" and qri will create a mock registry, we'll use this in tests elsewhere.
Long term it'd be nice to not have to bundle testing code with our production binary, but the overhead of maintaining a testing-oriented binary is a little too much at the moment.
=> feat(mock registry): add support for mock registry config

cmd/fsi.go, cmd/fsi_test.go, fsi/fsi.go, fsi/fsi_test.go, go.sum
closes #906
added some basic tests to make sure this works as expected
=> fix(fsi unlink): unlink command removes .qri-ref file

cmd/registry.go
small proxies for signup via the command line. We can expand on these more in the future.
=> feat(registry): add signup & prove subcommands

CONTRIBUTOR.md
code of conduct link result in Not found
=> docs(CONTRIBUTOR.md): Update code of conduct link

api/datasets.go, lib/datasets.go
Hook the `lib.Get` (which fetches `Stats` if `Selection="stats"`, into the `statsHandler`. `lib.Get` correctly fetches fsi datasets as well as versioned datasets.
If we don't have a structure, such as a case where we are using `fsi` and the user has removed their `structure.json`, stats should detect a structure and use that detected structure.schema to calculate stats.
=> fix(stats): gets stats with no structure

go.mod, go.sum, lib/diff_test.go, lib/lib_test.go
lol can't believe we don't have the testRunner pattern properly in lib yet. This uses the current tests in place, and adds a test that proves case sensitivity at the `lib` level.
=> test(lib): refactor diff tests into testRunner

cmd/search_test.go
Run this test in a temporary directory. This prevents repo/logbook.qfb from being created when the test runs.
=> fix(search): Run TestSearchRun in a tmp directory

api/api.go, api/websocket.go, base/component/list_dir.go, base/component/list_dir_test.go, go.mod, go.sum, lib/lib.go, watchfs/event.go, watchfs/watchfs.go, watchfs/watchfs_test.go
Open a websocket server that clients can connect to. Watch filesystem using fsnotify. The paths to watch are all FSI working directories. If files are created, modified, or deleted in those directories then an event is sent to all websocket clients.
=> feat(websocket): Open websocket server, watch filesystem for events.

cmd/registry.go
we had someone ask in the discord how to connect to an existing qri.cloud account, and I realized we haven't documented these commands at all.
=> docs(cmd): document registry signup and prove commands

cmd/test_runner_test.go, lib/integration_test.go, lib/remote.go, repo/test/generator.go, repo/test/temp_repo.go
wanted to get this test in place to both prove things are working properly in go land, and lay the foundation for writing this same test as an e2e test on desktop.
=> test(TwoActorRegistryIntegration): lib-level integration test showing logsync & clone behaviour

api/websocket.go, event/event.go, event/event_test.go, event/fsi.go, lib/fsi.go, lib/lib.go, watchfs/watchfs.go
hey hey @dustmop here's an initial implementation of an event package with an example. What do you think of this API?
=> feat(event): package event implements an event bus

base/base_test.go, base/save.go, cmd/diff.go, cmd/fsi.go, cmd/get.go, cmd/log.go, cmd/publish.go, cmd/remove.go, cmd/render.go, cmd/restore.go, cmd/save.go, cmd/validate.go, p2p/test/ipfs.go, repo/mem_repo.go
Found an issue with dry run. This addresses
we really need a dry run integration test.
=> fix(base): dry run works, doesn't write to logbook or dscache

.circleci/config.yml, .circleci/user_benchmarks.sh
closes #1112. This test will run & publish an update to [qri_eng/qri_cli_user_benchmarks](https://qri.cloud/qri_eng/qri_cli_user_benchmarks) whenever we push to master. Now that we can measure performance, we'll know when it's better 😄
=> chore(circleci): add performance benchmarks on master branch push

cmd/cmd_test.go
Since it was written, this test has been obsoleted by smaller tests that check the results of individual commands. It isn't particularily covering anything unique. It also has the potential to corrupt a developer's repo due to how it is calling setup. Remove it and continue making integration tests that follow particular user stories.
=> test(cmd): Remove the old cmd integration test

base/body_test.go
Small fix to the body fetch tests as the responses are not consistent with the expected value.
=> test(body): update expected message for missing host in url

cmd/fsi_integration_test.go, cmd/remove_integration_test.go, fsi/fsi.go, lib/datasets.go
=> fix(fsi): qri remove --all --force should not fail on low value files

api/log.go, api/remote.go, base/log.go, base/log_test.go, cmd/fetch.go, cmd/fetch_test.go, cmd/log.go, lib/log.go, lib/remote.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/http_test.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p_test.go, repo/ref/convert.go, repo/ref/convert_test.go
WIP, amending PR with comments in the code.
Applies to issue:
https://github.com/qri-io/qri/issues/1218
Related PR:
https://github.com/qri-io/qri/pull/1187
Parent issue:
https://github.com/qri-io/qri/issues/1120
=> fix(fetch): fetch should return DatasetLogItems and added tests

lib/config.go, lib/datasets.go, lib/diff.go, lib/export.go, lib/fsi.go, lib/lib.go, lib/log.go, lib/peers.go, lib/profile.go, lib/registry.go, lib/remote.go, lib/render.go, lib/search.go, lib/sql.go, lib/update.go
https://github.com/qri-io/qri/issues/1227
=> fix(rpc): better error messages on RPC EOF

lib/lib.go
Fixes https://github.com/qri-io/qri/issues/813
=> fix(rpc): registered json.RawMessage for gob encoding

base/dataset.go, cmd/print.go, cmd/qri.go, lib/datasets.go
This is the first of several things I want to do under this PR so will keep it generic for now and clean up later.
Starting off with the `--no-prompt` and `--no-color` flags.
=> fix(cmd): general fixes to cmd behavior

cmd/registry.go
Fixes https://github.com/qri-io/qri/issues/1067
=> fix(cmd): signup should provide feedback on success

cmd/stats.go, cmd/stats_test.go
=> fix(cmd): stats command works with an FSI directory

cmd/checkout.go, cmd/checkout_test.go, fsi/fsi.go, lib/fsi.go
Fixes https://github.com/qri-io/qri/issues/1195
=> Fix checkout dirs & allow checkout to specify directory on CLI

cmd/stats.go, cmd/stats_test.go
This PR adds effective pretty printing to the `qri stats` command.
=> [GH-1264] Fix qri stats pretty printing

api/api.go, api/api_test.go, api/transports.go, api/websocket.go, cmd/cmd_test.go, cmd/connect_test.go, cmd/fetch_test.go, config/api.go, config/config.go, config/migrate/migrate.go, config/readme.md, config/rpc.go, config/testdata/default.yaml, config/testdata/simple.yaml, go.mod, go.sum, lib/lib.go, lib/peers_test.go
Addresses https://github.com/qri-io/qri/issues/1345
Builds on to of https://github.com/qri-io/qri/pull/1367
Please test locally as well due to the config migration. Play with dummy repo's though.
Once approved this will first be staged by rebasing to a migration branch.
=> refactor(config): use multiaddr and migrate config

.github/1-bug-report.md, .github/2-feature-request.md, .github/3-support-request.md
New. Issue templates for Bug report, Feature request and
Support request (refer to Discord)
Closes #1362
=> docs: add issue templates

logbook/logbook.go, logbook/logbook_test.go, logbook/types.go
closes #1406, this should help prevent any writes that shouldn't be happening (eg the root cause of #1384)
=> fix(logbook): enforce single-author permissions on write methods

config/migrate/migrate.go
Missing a new line in one spot, and a few other formatting adjustments.
=> refactor(migrate): adjust output format

Dockerfile, cmd/cmd.go, cmd/connect.go, cmd/print.go, cmd/qri.go, config/migrate/migrate.go, config/migrate/migrate_test.go, lib/lib.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/logsync.go
we were missing these, which is bad.
=> fix(logbook,logsync,cmd): round of fixes prior to release

go.mod, go.sum
Closes https://github.com/qri-io/qri/issues/1429
=> fix(linux): migration fix for copying on cross link device

base/component/list_dir.go, base/component/list_dir_test.go
=> fix(fsi): component filenames are case-insensitive

api/datasets.go, cmd/pull.go, lib/datasets.go
I very much owe tests for this.
=> feat(pull): set pulling source with remote flag on CLI & API

api/datasets.go, cmd/get.go, cmd/get_test.go, cmd/test_runner_test.go, lib/load.go, remote/mock_client.go
From a [lengthy chat on discord](https://discordapp.com/channels/497052800778502152/571427701475377152/753380113445421148), this PR makes get do the same thing as `sql`, with the caveat that we'll iterate on this interaction in the future
closes #1501
=> fix(get): get command auto-fetches

sql/qds/datasource_test.go, sql/sql.go
=> style(sql): Fix variable name typo

lib/websocket.go
Enables push/pull events over WS.
=> feat(progress): enable websocket push pull events

watchfs/watchfs.go, watchfs/watchfs_test.go
also adds test confirming the fix
=> fix(watchfs): `WatchAllFSIPaths` needs to call `watchPaths`

cmd/get.go, cmd/list.go, cmd/log.go, cmd/peers.go, cmd/search.go, go.mod, go.sum, registry/regserver/handlers/profile.go, registry/regserver/handlers/protector.go, registry/regserver/handlers/search.go, remote/remote.go
Closes https://github.com/qri-io/qri/issues/1382.
=> refactor(api): Move all uses of apiutil to qri/api/util

base/remove.go, p2p/profile_service.go, p2p/profile_service_test.go, p2p/resolve_ref_test.go, remote/client.go, remote/mock_client.go, repo/fs/fs.go, repo/mem_repo.go, repo/repo.go
Fixed typo in comment and message.
=> Fixed typo (occured -> occurred)

go.mod, go.sum
updating this dependency brings multi-block streaming for dsync
=> feat(dsync): update dsync to use multi-block streams over HTTP

api/api.go, config/api.go, lib/websocket.go, lib/websocket_test.go
Updating websockets to work over the same port.
=> refactor(ws): refactoring websockets to use same port as http API

go.mod, lib/datasets.go, lib/transform.go, remote/browse.go, transform/startf/exec_step.go
new preview create lets us make previews & still read body data downstream
=> fix(transform): don't write to out streams when nil, use updated preview.Create

base/dataset.go, base/dataset_test.go, lib/datasets.go, p2p/datasets.go, registry/regserver/mock.go, remote/browse.go, transform/startf/qri/qri.go
and switch to our chosen `offset,limit` arg ordering
=> fix(base.ListDatasets): support -1 limit to list all datasets

lib/datasets_test.go, lib/dispatch.go, lib/http.go, lib/params.go
Addresses https://github.com/qri-io/qri/issues/1657
=> fix(http): fix httpClient error checking

api/api.go, api/fsi_test.go, api/log.go, cmd/log.go, lib/api.go, lib/integration_test.go, lib/lib_test.go, lib/log.go, lib/log_test.go, lib/rpc.go
=> refactor(log): RPC > HTTP & API for log

api/api.go, api/sql.go, api/sql_test.go, cmd/sql.go, lib/http.go, lib/integration_test.go, lib/lib.go, lib/lib_test.go, lib/rpc.go, lib/sql.go
=> refactor(sql): RPC > HTTP & API for sql

api/api.go, api/render.go, api/render_test.go, cmd/fsi_integration_test.go, cmd/render.go, lib/api.go, lib/http.go, lib/lib_test.go, lib/render.go, lib/render_test.go, lib/rpc.go
=> refactor(render): RPC > HTTP & API for render

api/search.go, cmd/search.go, lib/integration_test.go, lib/lib_test.go, lib/rpc.go, lib/search.go, lib/search_test.go
=> refactor(search): RPC > HTTP & API for search

api/registry.go, cmd/registry.go, lib/lib_test.go, lib/registry.go, lib/registry_test.go, lib/rpc.go
=> refactor(registry): RPC > HTTP & API for registry

api/api.go, api/datasets.go, api/remote.go, api/testdata/api.snapshot, api/util/errors.go, cmd/access.go, cmd/checkout.go, cmd/fsi.go, cmd/init.go, cmd/restore.go, cmd/status.go, cmd/whatchanged.go, lib/api.go, lib/datasets.go, lib/datasets_test.go, lib/integration_test.go, lib/scope.go, lib/test_runner_test.go
Finish dataset dispatch refactor
depends on #1701
=> refactor(dataset): finish dataset dispatch refactor

api/api.go, api/api_test.go, api/peers.go, cmd/peers.go, lib/api.go, lib/http.go, lib/lib_test.go, lib/peers.go, lib/peers_test.go, lib/rpc.go
=> refactor(peers): RPC > HTTP & API for peers

auth/token/token.go, auth/token/token_test.go, cmd/print.go, cmd/qri.go, lib/access.go, lib/dispatch.go, lib/lib.go, profile/store.go
closes #1717 
read above issue for context!
=> fix(api, token): dataset lib methods now working with http rpc

.circleci/config.yml, Makefile, docs/api_docs.go, docs/go.mod
Closes: https://github.com/qri-io/qri/issues/1771
Depends on: https://github.com/qri-io/qri/pull/1772
=> fix(oas): add open api spec tests to CI and makefile

sql/sql_arm.go
cherry picks single commit from branch `release-0.10.0` branch by @dustmop, so that only the version bump and change report is in the release commit
=> fix(sql): Fix sql command for arm build

auth/key/store.go, base/render_readme.go, profile/store.go
Addresses https://github.com/qri-io/qrimatic/issues/181 and sets the stage for https://github.com/qri-io/cloud/issues/506
=> fix(readme): readme urls are linked properly now

api/api.go, api/auth.go, auth/auth_test.go, auth/token/token.go, auth/token/token_provider.go, lib/lib.go
Part of: https://github.com/qri-io/qri/issues/1806
There will be a follow up PR that deals with aligning the token claims with what is expected for interop with cloud. 
Also it's still outstanding to do: https://github.com/qri-io/qri/issues/1810, https://github.com/qri-io/qri/issues/1811, https://github.com/qri-io/qri/issues/1812
=> feat(token): add and implement token provider interface

automation/orchestrator.go, automation/orchestrator_test.go, automation/run/run.go, automation/run/run_test.go, automation/run/store.go, automation/run/store_test.go, automation/spec/run.go, automation/spec/workflow_store.go, automation/workflow/store.go, automation/workflow/store_test.go, automation/workflow/workflow.go, base/params/list.go, lib/datasets.go
=> feat(run): add `run.Store` interface, spec tests, and implement `run.MemStore`

.circleci/config.yml, docs/api_doc_template.yaml, docs/api_docs.go
this populates more response examples in documentation with useful data envelopes
=> docs(api): add types from dataset & dsref packages

lib/automation.go
We accounted for context cancellations when publishing the deploy
events, BUT we did not acccount for context cancellations when using the
scope itself as a parameter for the `Save` and `WorkflowSave` functions
that the `Deploy` function itself calls.
We need a scope that will outlast the deploy request. We construct a
scope using the instance, source, and the original scope's `AppContext`.
=> fix(lib): adjust `Deploy` scope

automation/orchestrator.go, automation/run/filestore.go, automation/run/filestore_test.go, automation/run/run.go, automation/run/store.go, automation/workflow/filestore.go, automation/workflow/filestore_test.go, automation/workflow/store.go, lib/lib.go
=> feat(run, workflow): add file store implementations of `workflow.Store` and `run.Store`

automation/run/run.go
=> refactor(run): rename `StepState` deserialization object

automation/orchestrator.go, automation/orchestrator_test.go, automation/trigger/cron.go, automation/trigger/cron_test.go
Also, adjusts `CronTrigger.Advance` method to have the `nextRunStart` be one period after the current time.
=> fix(automation): update `Listeners` after the `Workflow` has been changed

automation/orchestrator.go, automation/orchestrator_test.go, automation/spec/workflow_store.go, automation/workflow/filestore.go, automation/workflow/filestore_test.go, automation/workflow/store.go, automation/workflow/workflow.go, automation/workflow/workflow_test.go, collection/collection.go, event/automation.go, lib/automation.go
Depends on https://github.com/qri-io/qri/pull/1852
=> refactor(workflow): replace datasetID with initID

api/api_test.go, api/open_api_3.yaml, api/spec/testdata/automation.json, api/test_runner_test.go, automation/orchestrator.go, automation/orchestrator_test.go, automation/workflow/wftest/testdata/no_changes/expect.workflow.json, automation/workflow/wftest/testdata/no_changes/input.dataset.json, automation/workflow/wftest/testdata/no_changes/input.workflow.json, automation/workflow/wftest/testdata/now/expect.workflow.json, automation/workflow/wftest/testdata/now/input.dataset.json, automation/workflow/wftest/testdata/now/input.workflow.json, automation/workflow/wftest/wftest.go, automation/workflow/wftest/wftest_test.go, automation/workflow/workflow.go, lib/automation.go, lib/automation_test.go, lib/http/api.go, lib/lib.go
closes #1863 
closes #1849 
----
to reviewers: the last two commits could really have been in their own PR, but I didn't like the idea of adding these endpoints without ensuring they were tested in the API spec tests!
=> feat(lib): add lib `Run` and lib `Workflow` methods and endpoints

logbook/logbook.go
this is an incomplete interface, but gets us a short-term solution for opstores that need an interface for transactional logbook updates. To make use of this an posture implementation should add a new method, where the implementation should be consistent with `MergeLog` semantics. The following should work:
```
func (s *Opstore) PutLog(ctx context.Context, l *oplog.Log) error {
return  s.MergeLog(l)
}
```
This interface is **not** implemented for all write operations yet, but provides a mechanism to do so in follow up changes
=> feat(logbook): add `logPutter` interface for transactional saves

collection/collection.go, collection/collection_assert_test.go, dscache/dscache.go, event/dataset.go, event/logbook.go, event/transform.go, logbook/logbook.go, transform/transform.go, transform/transform_test.go
=> fix(collection): clean up run tracking

lib/automation.go
Until we can save a dataset without a body or structure, the `Deploy`
path is going to handle the "running" of any transforms. In order for
the frontend to coordinate events, it needs to know this `runID`. If we
detect that we will be "apply"ing a transform during a "save" in a
"deploy", we must create a `runID` early & pass it to the frontend
through the deploy events ASAP. When we can save a dataset without a
structure or a body, then these pieces can be removed.
closes #1928 and unblocks qri-io/frontend#258
=> fix(lib): hack - deploy path needs to create a `runID`

lib/websocket/websocket.go, lib/websocket/websocket_test.go
We got a few segfaults on `unsubscribeConn` due to the id returning a nil set presumably due to emptying all connections without deleting the actual connection. Not worth keeping a full ref count on each and adding lots of code around it, it's enough to just garbage collect later here.
=> fix(ws): fix nil pointer

api/util/responses.go, api/util/responses_test.go, cmd/list.go, lib/automation_test.go, lib/collection.go, lib/collection_test.go, lib/cursor.go, lib/cursor_test.go, lib/dispatch.go, lib/http.go, lib/lib_test.go, lib/params.go, lib/scope.go, remote/server.go
A working Cursor implementation that can work generically for many methods. For now, use it just for collection.List. This includes an http response with the json data needed to fetch the next page.
=> feat(dispatch): Cursor for collection.List pagination

api/testdata/expect/TestDatasetGet.test_ds.json, cmd/get_test.go, cmd/pull_test.go, lib/datasets.go, lib/datasets_test.go
=> fix(lib): `/get` endpoint should return preview if no `selector` given

transform/staticlark/analyze.go, transform/staticlark/call_graph.go, transform/staticlark/control_flow_test.go, transform/staticlark/dataflow.go, transform/staticlark/dataflow_test.go, transform/staticlark/environment.go, transform/staticlark/functions.go, transform/staticlark/testdata/call_trace.star, transform/staticlark/testdata/safety_funcs.star, transform/staticlark/unit.go, transform/staticlark/unit_test.go
An early implementation of dataflow analysis for starlark. Some caveats:
* control flow not being used, only linear flow is analyzed
* no lexical scoping nor inner functions
* axioms need to be populated
=> feat(staticlark): Dataflow analysis for sensitive data

lib/collection.go
Also, allows fetching a dataset from the collection that is not in your own collection
closes #1985
=> fix(lib): use `username` parameter in `lib.List`
