qri-io/qri

api/handlers/datasets.go, api/handlers/peers.go, api/server.go, api/server_test.go, cmd/add.go
Cleaning up api functions:
- needed to open file with DataFilename path and add to initParams{} in order to get Init() to work
- remove peer and peernamespace functions that were refactored into /[peername] and /list/[peername]
=> refactor(api): fix add bugs and remove unneeded peer functions

Makefile
peers with outdated packages have run into issues building qri, adding the -u flag to step one of 'make build' should address this.
related: #217
=> fix(build): always fetch dependencies from the network

cmd/connections.go, cmd/info.go, cmd/peers.go, cmd/search.go, cmd/setup.go, cmd/version.go
At https://www.youtube.com/watch?v=1vmwTrN1Pl4&t=5m48s I noticed that the descriptions of the commands are inconsistently capitalized. This fixes the ones I could find in the repo. "Help" seems to be baked in, so will need to be fixed differently.
=> Fix capitalization inconsistency

api/context_test.go, api/server_test.go, api/testdata/historyResponse.json, api/testdata/listResponse.json, api/testdata/saveResponse.json, api/testdata/saveResponseMeta.json, cmd/cmd_test.go, cmd/connect.go, core/datasets.go, core/datasets_test.go, core/history_test.go, core/profile.go, core/search_test.go, p2p/message_test.go, repo/fs/fs_test.go
=> feat(JSON): support JSON as a first-class citizen in qri

api/config.go, api/server.go, core/self_update.go, core/self_update_test.go
So, we want to be able to modify & update the webapp independent of qri, to do that, I've created a new dnslink entry "webapp.qri.io" that can be resolved with `ipns name resolve webapp.qri.io`. For kicks I've also added ipns name resolving to the api server (this should be removed when we refactor
to just using regular IPFS API bindings).
=> feat(webapp): fetch webapp hash via dnslink 

.codeclimate.yml
ripped directly from ipfs/go-ipfs without any reading or consideration whatsoever. Sounds responsible, right?
=> chore(codeclimate): add initial codeclimate configuration

api/server.go, api/server_test.go, cmd/add.go, cmd/cmd_test.go, cmd/config.go, cmd/connect.go, cmd/repo.go, cmd/setup.go, config/api.go, config/logging.go, config/p2p.go, p2p/bootstrap.go, p2p/discovery.go, p2p/node.go, p2p/p2p.go, p2p/peers.go, repo/fs/files.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/fs/profile_store.go, repo/profile/id.go
makes inroads on #336
Summary:
* fsrepo no longer keeps `profile.json`, it instead relies on being provided a `config.Profile` when `NewRepo` is called
* added a check to the test suite to make sure it wouldn't interfere with an already-running repo
* I _think_ fsrepo's peerstore might have been writing invalid json, but that might have been b/c of this tests/live server footgun I found. I'll investigate further later & PR if necessary
=> refactor(fsrepo): remove profile.json storage, fix peerstore invalid marshaling.

cmd/config.go, cmd/print.go, cmd/setup.go, config/profile.go
while testing out enviorment variable configuration I needed a quick way to get config an existing config as JSON, and realized it may be helpful in other places. This adds export as a subcommand of
config that by default prints a json blob of the current config file with private keys removed. I've added --with-private-keys to add in the private keys, and a few other flags to switch format to yaml or pick an output file.
=> feat(cmd.Config): added qri config export command

api/root.go, api/server.go, api/templates.go, api/webapp.go, cmd/repo.go, config/webapp.go, repo/fs/fs.go
using the compiled app delivered as a hash causes sad emoji when the api is up in read-only mode b/c then the user can't access the `/ipfs` endpoint on the api. To fix this I've cleaned up our webapp code a bit in the api package and now the frontend just loads "webapp.js", with new logic in the backend that knows what to do with that.
=> fix(webapp): hide webapp hash behind vanity url

api/server.go, cmd/cmd.go, cmd/cmd_test.go, cmd/connect.go, cmd/connect_test.go, cmd/root.go, cmd/setup.go, cmd/version.go, config/api.go
Version 0.3.0 went out the door with a bug that breaks the default
docker image command, sad! The problem was caused by switching the
"anonymous" flag from a cobra.BoolVarP to a cobra.BoolP.
When connect is run with --setup, we cheat heavily & just manually
invoke the setup cobra command on the spot. The problem with this
cheat is the setup command hasn't been properly allocated by cobra,
and so any flag set without a global variable reference isn't assigned
when commands are invoked in this manual way. In the long run we should
move away from this method entirely. The short solution would be to move
the contents of setupCmd.Run into a private func "doSetup", the better
way to do this would be to create a new setup core method.
To smooth the transition through these refactorings, I've …
=> fix(connect): fix errors caused by running connect with setup

api/root.go, api/server_test.go
@osterbit needs the root endpoint of our api to return a nice status code. GO GO FIX MEOW
=> refactor(api): make api root a status check

config/readme.md
Filled out config readme, to include info on the rpc, api, and webapp ports.
=> docs(config): expand config readme.md

.circleci/config.yml, DEVELOPERS.md, Makefile, api/profile.go, api/server.go, api/testdata/profileResponse.json, cmd/cmd_test.go, config/profile.go, config/profile_test.go, core/core_test.go, core/profile.go, core/profile_test.go, p2p/node.go, p2p/node_test.go, p2p/profile.go, repo/actions/dataset_test.go, repo/fs/fs.go, repo/fs/profile_store.go, repo/profile/profile.go, repo/profile/store.go, repo/ref_test.go, repo/test/test_repo.go
refator(api): use /profile/photo & /profile/poster as vanity enapoints
Similar to the situation we ran into shipping the webapp, readonly mode can and should prevent access to anything under the `/ipfs/` endpoint, which sadly includes profile photos & poster images. To get around this we'll use the same trick of hiding photos behind vanity urls.
In an effort to avoid API bloat, I've added these as elements of the previously under-used /profile/photo & /profile/poster GET endpoints. Both now accept query params for id (which is the profile ID) or peerneme. this is going to need some refinement & docs, but it'll work for now.
I've also removed .png image formats for posters & profiles so that these endpoints have an easy story for providing `Content-Type` headers.
Examples:
```
GET …
```
=> refactor: photo endpoints, mutex fixes, makefile updates

Makefile
Current error renders as:
Makefile:8: *** OPATH must be set
Since the shell will treat $G as a variable to evaluate, concatenating the result to `OPATH`.
=> chore(makefile): escape dollar sign so error displays correctly

cmd/data.go, cmd/info.go, cmd/rename.go
Logic surrounding the info command is just too convoluted right now. In the future it'd be great to get this working properly, but will require some pretty major refactoring at lower levels before that can be the case, so for now let's just turn it off.
=> refactor(infoCommand): make info command only work for datasets

cmd/connect.go, config/api.go
we missed a condition where `--setup` flag is provided but configuration details already exist.
=> fix(setup): fix config not loading if already found

cmd/config.go, config/api.go, config/api_test.go, config/cli.go, config/cli_test.go, config/config.go, config/config_test.go, config/logging.go, config/logging_test.go, config/p2p.go, config/p2p_test.go, config/profile.go, config/profile_test.go, config/registry.go, config/registry_test.go, config/repo.go, config/repo_test.go, config/rpc.go, config/rpc_test.go, config/store.go, config/store_test.go, config/webapp.go, config/webapp_test.go, core/config.go, core/profile.go, core/profile_test.go
closes #375 
* Moves the bulk of the functionality of GetConfig from the cmd/config.go file to the core/config.go file. Adds GetConfigParams.
=> feat(api/config): refactor cmd/config.go and add api/config.go

core/core.go, core/datasets.go, p2p/events_test.go, p2p/node.go, p2p/node_test.go, p2p/p2p_test.go, p2p/ping_test.go, p2p/profile_test.go, p2p/test/p2ptest.go, repo/test/test_repo.go
Will enable easier testing of p2p package. Also move NewTestRepo to repo/test, and create
NewDatasetRequests constructor that can take a QriNode parameter.
=> refactor(p2p): extract NewTestNetwork into its own p2ptest package

api/peers.go, cmd/connect.go, cmd/diff.go, cmd/peers.go, cmd/search.go, cmd/version.go, core/peers.go, p2p/peers.go, repo/profile/store.go
We've been lacking proper peer connection control for a while now, this upgrades the `qri peers connect` command to accept:
* `/ipfs/QmPeerId`
* qri profile ID
* peernames (must exist in cache)
* a full multiaddr string (same as our bootstrap addresses)
So all of the following should be valid:
* `qri peers connect /ipfs/QmTZxETL4YCCzB1yFx4GT1te68henVHD1XPQMkHZ1N22mm`
* `qr peers connect b5` _(only if you've seen peer b5 before)_
*  `qri peers connect QmSyDX5LYTiwQi861F5NAwdHrrnd1iRGsoEvCyzQMUyZ4W` (b5's profileID)
* `qri peers connect /ip4/130.211.198.23/tcp/4001/ipfs/QmNX9nSos8sRFvqGTwdEme6LQ8R1eJ8EuFgW32F9jjp2Pb`
the same for a new disconnect command, which explicitly closes a connection.
All of the above also applies to the api `/connect` endpoint, so:
* …
=> feat(peer connections): single peer connection control

p2p/datasets.go
Peer's datasetRefs were coming back with just the hash, not the full dataset.
=> fix(p2p.handleDatasetsList): peer's datasets now return fully hydrated

repo/actions/merge_events.go, repo/actions/merge_events_test.go, repo/events.go
To merge repos' EventLogs, compare the Events timestamp by timestamp until we find a mismatch.
Treat that mismatch as a conflict if the two events cannot be resolved, otherwise tell the merging
peers that they updates that need to be added to their EventLogs.
=> feat(repo): merge repos' EventLogs using a simple first attempt

api/profile_test.go, api/server_test.go, cmd/cmd_test.go, cmd/connect_test.go, core/setup_test.go
quick update to work with new registry code. This further decouples the two codebases so we should have to do this less in the future (at least on the testing frontier)
=> test(registry): switch to mock registery server package

api/server.go, cmd/render.go, cmd/repo.go, config/config.go, config/p2p.go, config/render.go, config/render_test.go, config/testdata/default.yaml, config/testdata/simple.yaml, core/core.go, core/core_test.go, core/render.go, core/render_test.go, core/self_update.go, core/self_update_test.go, repo/actions/dataset.go
Pumped about this one. I've realized we can get a long way by just executing templates against qri datasets, which have a rigid structure that makes templating much easier. So with that, I'd like to introduce a new command: `qri render`. `qri render` accepts a dataset name, executes a HTML template, using the specified dataset to populate template data. It has a few features:
* render uses the `template/html` package from golang. users of the Hugo static site generator will feel at home with this syntax
* users can provide custom templates with the --template argument
* if no template is specified, qri uses a default "stock" template that is resolved over IPFS
* this stock template is updated using IPNS, similar to the way we distribute app updates
* template fetching falls back to a P2P …
=> feat(render): add render command for executing templates against datasets

api/profile_test.go, api/server_test.go, cmd/cmd_test.go, cmd/connect_test.go, cmd/repo.go, core/core_test.go, core/datasets.go, core/datasets_test.go, core/history_test.go, core/peers_test.go, core/profile_test.go, core/render_test.go, core/search_test.go, core/setup_test.go, repo/actions/dataset.go, repo/actions/dataset_test.go, repo/actions/merge_events_test.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/graph_test.go, repo/mem_repo.go, repo/ref_test.go, repo/repo.go, repo/test/test_repo.go
we gave registries a few new tricks, and have started integrating them here. If a qri repo is configured with a registry, it will fire off notifications to the registry server within goroutines on dataset creation & deletion, which will start to build up a list of datasets on the registry side. This comes back to help users on core.datasetRequests.Get, which now includes a parallel check
to both p2p network *and* registries if we don't have a local copy.
The upside here is we can use registries to do checks if we aren't connect to p2p. If this goes as expected the next place to expand is adding search on the registry side, and then move on to tracking who has pinned what.
*might* make some inroads on #397
=> feat(registry.Datasets): initial dataset registry integration

cmd/cmd.go
Taking an idea from rust's RUST_BACKTRACE, show a stack dump on error only if
the environment variable QRI_BACKTRACE is defined. This prevents the need to
comment and uncomment code blocks (which may get accidentally commited to git)
in order to get valuable debugging information.
=> feat(backtrace): Show error's stack if QRI_BACKTRACE is defined

api/datasets.go, cmd/data.go, core/datasets.go, core/datasets_test.go
Use new utilities Copy and PagedReader instead of copying entries manually. Rename StructuredData (the method) to LookupBody, rename StructuredData (the struct) to LookupResult.
=> refactor(datasets): Use Copy and PagedReader. Rename StructuredData.

cmd/cmd_test.go, cmd/export.go, cmd/save.go
closes #435 
Also replaces redundant --data flag with --no-data flag (data is always exported by default, and if there are no flags then just the data will export)
=> feat(cmd/export): specify data format using --data-format flag

cmd/add.go, cmd/cmd.go, cmd/print.go, cmd/root.go, cmd/save.go, core/datasets.go, repo/actions/dataset.go, repo/actions/dataset_test.go, repo/actions/transform.go, repo/test/test_dataset_actions.go, repo/test/test_repo.go
At some point someone isn't going to read the documentation on how transform.config works, not realize that we record all configuration details, create a script that asks a user to put API keys into a config slot, and qri will dox those keys. This will make me sad.
To prevent this I'm adding in an explicit codepath for secrets, one that currently only works with the
command line, and comes with a warning if the user tries to provide secrets to `qri add` or `qri save`.
By providing explicit features & docs on how to interact with secret information, and throwing warnings
around the use of this information, I believe we'll reduce the chances people will misuse features like
config. @osterbit pointed to the "danger zone" on github repo settings as a good example of warning users when they're …
=> feat(transform secrets): supply secrets to transforms

cmd/add.go, cmd/cmd_test.go, cmd/registry.go, cmd/repo.go, cmd/save.go, core/core.go, core/core_test.go, core/datasets.go, core/registry.go, repo/actions/dataset.go, repo/actions/registry.go
I've refactored a bunch of the logic around working with registries to make the process more explicit & controllable.
=> feat(registry cmd): add commands for working with registries

cmd/config.go, config/config.go, config/config_test.go
updated config Set method to support setting map[string]interface{} values
closes #450
=> fix(config): set map values with config set command

lib/datasets.go
this is a hack-fix for now because in the long run we're hoping to get away from the net/rpc package that's causing these problems in the first place (hoping to replace with gRPC).
closes #449
=> fix(list peer datasets): fix to make listing peer datasets work

.circleci/config.yml, cmd/body.go, cmd/factory.go, cmd/get.go, cmd/qri.go, cmd/use.go, lib/datasets.go, lib/history.go, lib/lib.go, lib/lib_test.go, lib/render.go, lib/selection.go, lib/selection_test.go, repo/actions/dataset_test.go, repo/actions/select.go, repo/fs/files.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/graph_test.go, repo/mem_repo.go, repo/ref.go, repo/repo.go, repo/test/test.go, repo/test/test_dataset_actions.go, repo/test/test_repo.go
Two things showed up while working on tutorials:
1. We haven't built a way to actually _get_ dataset info from the command line. Currently we have `qri info`, which only displays a summary.
2. constantly retyping dataset names has officially gotten too irritating.
For the retyping problem, I think we should steal the concept of "USE" from database land to set the current dataset. For example, in postgres's `psql` tool, the command `USE [database_name]` sets the current database you're interacting with. So for us I've first plumbed the concept of a "Reference Selection" as an opt-in interface in the repo package:
```golang
// RefSelector is an interface for supporting reference selection
// a reference selection is a slice of references intended for using
// in dataset operations
type …
```
=> feat(use, get): added use and get commands

cmd/add.go, cmd/cmd.go, cmd/remove.go, cmd/save.go
This command-line invocation:
qri add --body=some_rows.json new_dataset
would previously act as follows:
added new dataset me/some_rowsjson@QmBlahBlah/ipfs/QmBlahBlah
but now acts like:
added new dataset me/new_dataset@QmBlahBlah/ipfs/QmBlahBlah
=> fix(cmd): Wrap how DatasetRefs are parsed for better cmd behavior.

api/testdata/statusResponse.json, cmd/cmd_test.go, cmd/connect.go, cmd/qri.go, cmd/registry.go, cmd/remove_test.go, cmd/rename_test.go, cmd/render_test.go, cmd/save.go, cmd/save_test.go, cmd/search_test.go, cmd/test_factory.go, cmd/use_test.go, cmd/validate_test.go, lib/datasets.go, lib/datasets_test.go, lib/registry.go, lib/search.go, repo/actions/registry.go, repo/repo.go
Over on the registry repo we've added interfaces for registries to accept requests to pin data. Profiles that are connected to the registry can sign a request that the registry copy the data.
This PR adapts `qri registry publish` to also submit a request to pin if a registry is present. The process works like this:
1. User needs a local dataset they've created. They run `qri registry publish me/foo`
2. the user isn't connected to the p2p network, qri connects, and write's down it's local addresses
3. qri adds the full datasetRef of `me/foo` (most importantly, the `/ipfs/QmFooHash` bit), and those local addresses into a call to `regclient.Pin`. Those are sent to the registry server. In a request that'll take a little time...
4. Over on the registry side, an ipfs node is asked to pin the …
=> feat: Pin on publish

api/server_test.go, lib/datasets.go, lib/lib.go
By registering interface array and interface map types with gob, we should hopefully avoid all future gob encoding erorrs. Revert commit d9f78058adb which added a work-around for this error; it isn't needed anymore.
=> fix(rpc): Register types with gob to avoid "reading body EOF" errors

cmd/get.go, cmd/get_test.go, cmd/render_test.go, config/p2p.go, lib/render.go, lib/render_test.go
this change ensures we _always_ have a template to render into. Previously we were trying to keep sync on templates from the d.web but it's a little too flakie for the moment. I'd like to add default template updating at some point in the future, but for now reducing the number of external dependencies leads to software that works better. The supplied default is pretty sparse, but it's a start.
This also sneaks in a quick fix for #492
=> refactor(render): replace template lookup with hardcoded template

cmd/rename_test.go, cmd/save_test.go, lib/datasets.go, lib/datasets_test.go, lib/history.go, lib/render.go, repo/actions/merge_events_test.go, repo/mem_repo.go, repo/ref.go, repo/ref_test.go, repo/test/test_repo.go
Previously, CanonicalizeDatasetRef had 2 main steps: canonicalizing the profile
(turning "me" into the user's peername), and then filling in fields from the
local repo. If the dataset did not exist in the local repo (because it was
a remote dataset), the function would ignore GetRef's error, and just continue
on. This fragile behavior led to bad things, like many callers duplicating work
such as caling GetRef after CanonicalizeDatasetRef, or certain methods
displaying non-sensical error messages.
Instead, have CanonicalizeDatasetRef return repo.ErrNotFound if the reference
is non-local. Callers can handle this error code as needed, such as displaying
a more sensible error, or succeeding anyway (in the case of `rename`, which
expects the reference to not be found), or contacting a remote …
=> refactor(dataset): Change CanonicalizeDatasetRef's return semantics.

Makefile, cmd/add.go, cmd/body.go, cmd/cmd.go, cmd/config.go, cmd/connect.go, cmd/diff.go, cmd/export.go, cmd/get.go, cmd/info.go, cmd/list.go, cmd/log.go, cmd/peers.go, cmd/registry.go, cmd/remove.go, cmd/rename.go, cmd/render.go, cmd/save.go, cmd/search.go, cmd/setup.go, cmd/use.go, cmd/validate.go, cmd/version.go, docs/docs.go, repo/search/search.go
While writing the [RFC CLI commands](qri-io/rfcs#14) document, I figured I would go through and update the documentation on the CLI commands, if any are outdated.
=> docs(cmd): updating cmd documentation

api/server_test.go, cmd/get.go, lib/datasets.go, lib/datasets_test.go, repo/actions/select.go
Get method written so that it is used by both cmd/ and api/. Follows the new
guideline set out by #519, moving nearly all the logic from lib/ to actions/.
Logic which is specific to the command-line, selecting parts of a dataset
using a path, moved up a level to the cmd/ package.
Get can now be used to retrieve info about local and remote datasets, from
both command-line and api server. Fixes #509, #479 #397, and possibly others.
Clears the way to merging `body` into `get` in a future PR.
Breaks ability to `get` multiple datasets at once.
=> fix(get): Get completely reworked to function better

api/open_api_2.yaml, api/open_api_3.yaml, cmd/cmd.go
Future iterations will add code to generate html documentation for the API using the Makefile.
This PR also includes a change to our `cmd/printErr` function. `printErr` will print the user friendly `lib.Error.Message()` if the err given is a `lib.Error`, a normal `error` will print if no message is included.
=> feat(api/open_api): add open api 2.0 and 3.0 specifications to the api package

config/p2p.go, p2p/node.go
Currently, the p2p tests (as well as some tests in lib) spend a lot of time
generating actual crypto keys due to calling DefaultP2P, which are then
replaced by test keys from the libp2p package. Avoiding this useless work
speeds up the p2p tests by about 5x.
Performance numbers from before this change, taken from https://github.com/qri-io/dataset/pull/141:
```
Run 0
ok      github.com/qri-io/qri/api      18.428s
ok      github.com/qri-io/qri/cmd      59.639s
ok      github.com/qri-io/qri/config   46.602s
ok      github.com/qri-io/qri/lib      52.682s
ok      github.com/qri-io/qri/p2p      40.562s
Run 1
ok      github.com/qri-io/qri/api      21.280s
ok      github.com/qri-io/qri/cmd      55.533s
ok      github.com/qri-io/qri/config   51.034s
ok      github.com/qri-io/qri/lib      44.018s …
```
=> fix(p2p): Avoid generating p2p keys in DefaultP2P, for faster tests

cmd/cmd.go, cmd/system.go, cmd/system_windows.go
If the user is running qri without having a sufficiently large enough value for the "open files limit", their IPFS instance can start to fill with the error "too many open files". Setting this value at startup avoids this issue.
=> fix(cmd): Set number of open files limit at startup.

api/datasets.go
closes #532 
But only in the sense that it fixes the immediate bug, not necessarily the underlying structure that may need to change.
Asking for this to be merged tho, since without it the frontend freaks out when trying to get a peer's dataset body
=> fix(api.Body): fix bug that returns error when getting a peers body

actions/body.go, actions/dataset.go, actions/transform.go, api/datasets.go
Ok so this isn't much of a feature, but people like the word "feat" in change logs, so whatever.
*fixes*:
* API adjustment so that `POST`ing to `/new` and `/save` with form data behave the same way
* fixes an error returning body data that isn't JSON from POST to `/new` and `/save`
*refactors*:
* updates to new skytf.ExecFile signature, removes a reduntant read through body data in the process
ugh I need to get better at splittin' up my commits.
=> feat(ConvertBodyFile): new action to convert body data

cmd/new.go
=> fix(new): Take absolute path to body file before loading it in `new`.

p2p/connected.go, p2p/dataset_test.go, p2p/datasets_test.go, p2p/events_test.go, p2p/log_test.go, p2p/node.go, p2p/peers.go, p2p/ping_test.go, p2p/profile.go, p2p/profile_test.go, p2p/qri_peers_test.go
Right now, your peer sends it's profile to a peer. The peer sends its own profile back, but doesn't save the incoming profile.
This is causing certain peers to not show up in our peers list, even when we do have an underlying connection.
=> fix(p2p.RequestProfile, p2p.handleProfile): receiving peer does not save profile to repo

actions/dataset_ref_test.go, actions/dataset_test.go, actions/peers_test.go, lib/datasets_test.go, p2p/bootstrap.go, p2p/connected_test.go, p2p/dataset_test.go, p2p/datasets_test.go, p2p/discovery.go, p2p/events_test.go, p2p/log_test.go, p2p/network_notifee.go, p2p/node.go, p2p/p2p.go, p2p/peers.go, p2p/peers_test.go, p2p/ping_test.go, p2p/profile_test.go, p2p/qri_peers.go, p2p/qri_peers_test.go, p2p/resolve_ref_test.go, p2p/test/p2ptest.go, p2p/test/p2ptest_test.go, p2p/test/testable_node_test.go
UpgradeToQriConnection expects:
- we have connections to each peer
- we have the addrs of each peer
- we have a tag on each peer
- we have the protocols each peer supports
UpgradeToQriConnection then:
- records if the peer supports the qri protocol
- tags the ConnManager that this is a qri connection, and therefore more important
- requests the profile of that peer
- requests the ids of the peers that that peer knows.
- requests the profiles for those peers
This pr also formalizes the differences between `ConnectNodes` and `ConnectQriNodes` and adjusts tests to use `ConnectQriNodes`.
A basic p2p connection:
- we have the connections listed in the network
- we have the addrs in the peerstore
- we have a basic tag in the ConnManager
- we know what protocols the peer understands
A Qri p2p …
=> Refactor(AddQriPeer): rename `AddQriPeer` to `UpgradeToQriConnection` and formalize it's role

p2p/discovery.go
well, this one is funny. In a refactor a while ago, I missed switching `conf.BoostrapAddrs` -> `conf.QriBootstrapAddrs`. The result of this oversight is qri connect bootstraps to *no* peers, which means the network seems empty. Sad emoji. Programming is hard.
=> fix(bootstrap peers): fix network not ever contacting bootstrap peers

cmd/factory.go, lib/search.go, repo/fs/fs.go, repo/fs/profile_store.go
and other things caught by `go vet  ./...`, we should probably get `gometalinter` running in CI, which has `go vet` built in.
=> fix(fs Profile Store): fix lock pass-by-value error

actions/dataset.go, actions/transform.go, actions/transform_test.go, api/datasets.go, base/dataset.go, lib/datasets.go, lib/file.go
We haven't yet moved the initDataset functionality into SaveDataset.
In the API, we ignore the `dry_run` and `return_body` form fields, so all calls to save from the API are actually saving the dataset, not actually doing a dry_run
This code does a hacky work around on the MemRepo-and-loading-a-previous-dataset known bug, by removing the dataset's PreviousPath, when we are doing a dryrun.
If ReturnBody is true, we return the dataset body as as bodyBytes, using the addBodyFile function
=> refactor(api.saveHandler, lib.Save, base.CreateDataset): add ability to use DryRun and ReturnBody flags

actions/dataset.go, actions/transform.go, actions/transform_test.go, lib/file.go
When finished, this PR should implement the first step of [RFC0020](https://github.com/qri-io/rfcs/blob/master/text/0020-distingush_manual_vs_scripted_transforms.md)
=> refactor: Distinguish Manual & Scripted Tranforms

Makefile, actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, actions/diff_test.go, actions/recall.go, actions/recall_test.go, actions/transform.go, base/dataset.go, base/dataset_prepare.go, base/dataset_prepare_test.go, base/dataset_test.go, base/revisions.go, base/revisions_test.go, cmd/save.go, cmd/save_test.go, cmd/update.go, lib/datasets.go, lib/datasets_test.go, lib/file.go, lib/lib_test.go, lib/peers_test.go, lib/testdata/now_tf/input.dataset.json, lib/testdata/now_tf/transform.star, rev/rev.go, rev/rev_test.go
When finished, this PR should implement the bulk of [RFC0020](https://github.com/qri-io/rfcs/blob/master/text/0020-distingush_manual_vs_scripted_transforms.md), excluding field-level exclusion checks
* ~~[ ] lib:~~
* ~~[ ] an integration test on lib that runs the tutorial from RFC 0020~~ _(this is better covered as a unit test on `actions.SaveDataset`)_
=> refactor: Mutually Exclusive Manual & Scripted Tranforms

repo/fs/refstore.go
this is causing silly stuff to be stored in `ds_refs.json`
=> fix(fs refstore): don't store DatasetPod in refstore

actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, api/datasets.go, base/dataset.go, base/dataset_test.go, cmd/save_test.go, lib/datasets.go, lib/lib_test.go
When a save command is run, and the new format is different from the format of the previous version, either return an error, or if the ConvertFormatToPrev flag is set on SaveParams, rewrite the body to match the previous version’s format. The API always sets ConvertFormatToPrev, but the command line does not (yet).
=> fix(format): Detect format change when saving, either error or rewrite

api/api.go, api/templates.go, api/transports.go, api/transports_test.go, api/webapp.go, api/webapp_test.go
Our webapp has gotten too complicated to reasonably serve as a single file. This PR adjusts the way we serve frontend stack files. We can compile our frontend down to a directory, and serve that CAFS directory behind the `/webapp/` endpoint. webapp code can come from the dweb and always be served consistently behind the `/webapp/` endpoint from api's webapp server. neat!
=> fix(webapp): restore webapp

cmd/cmd_test.go, cmd/testdata/movies/ds_ten.yaml
Prior to commit 00a30d3fb6c, trying to save a dataset with a bodypath at a relative path would erroneously use the current directory to try to resolve that path, instead of the directory that the dataset.yaml was in. This change adds a test case for this new, correct behavior. Note that you can restore this old, invalid behavior by commenting out the assignment to dsp.BodyPath in the function absDatasetPaths in /lib/file.go, currently line 130; doing so will also cause this test to fail.
As part of this test case, we're also doing something new: validating that the body of the saved dataset matches the input that the save command was given. This is accomplished by using the ipfs bindings to read the the body directory from our testRepo, exercising our full tech stack. In the future, it …
=> test(save): Test case for saving a dataset with a relative body path.

actions/registry.go, actions/registry_test.go, api/api_test.go, api/registry.go, cmd/registry.go, cmd/remove_test.go, cmd/save_test.go, lib/registry.go, lib/registry_test.go, repo/ref.go
Status is helpful on the cmd, but over the api and on the frontend, we want the actual dataset to be returned. We can infer from the response whether or not the dataset exists on the registry.
this pr adds:
`registryDatasetHandler`
`RegistryRequests.Get`
`actions.RegistryDataset`
and removes:
`statusRegistryHandler`
`RegistryRequests.Status`
`actions.Status`
and adjusts:
`cmd/registry.go` to use `RegistryRequests.Get`
`/registry/` GET endpoint to use `registryDatasetHandler`
=> refactor(registry): remove `status` and replace it with `registryDataset`

actions/peers.go, actions/peers_test.go, lib/peers.go
When getting Info for a peer, set the Online flag appropriately, to match the behavior of lib.List (peers.go). Do this by checking the other connected peers that are known to be online, and also checking if you yourself are online.
Cleanup some of the usage around ConnectedQriProfiles.
Fixes part 2 of #577.
=> feat(online): Set Online flag for peers when using lib.Info. Cleanups.

.github/CONTRIBUTING.md, CONTRIBUTOR.md, DEVELOPERS.md, cmd/add.go, cmd/export.go, cmd/list.go, cmd/publish.go, cmd/save.go
Looks like we never had a proper CONTRIBUTOR.md file like we do in the frontend. This modifies that file for use in the backend. Also, our DEVELOPERS.md file seems like it was just copy pasted over to the backend github, without changes that make it relevant for go
closes #619
=> docs(*): updating errors in docs

cmd/qri.go, config/config.go, config/config_test.go, config/migrate/migrate.go, config/p2p.go, config/testdata/simple.yaml, lib/config.go, lib/config_test.go
This PR adds a `Version` field the config file, and migrates any configuration that _doesn't_ have
=> fix(config migration): add config migration to update p2p.QriBootstrapAddrs

cmd/setup.go, config/config.go, config/migrate/migrate.go, config/p2p.go, config/profile.go, config/test_config.go, lib/peers_test.go, p2p/test/p2ptest.go
Now that no Config constructors are inefficiently adding p2p keys, rename the Default\*WithoutKeys methods so that they are just Default\*. Add a comment to config/config.go explaining that DefaultConfig does not contain any p2p keys, but that cmd/setup.go adds them.
=> refactor(config): Rename Config constructors.

cmd/body.go, cmd/cmd_test.go, cmd/export.go, cmd/factory.go, cmd/factory_test.go, cmd/qri.go, cmd/setup.go, lib/datasets.go
Prior to this change, both `qri body` and `qri setup` would fail with "repo not available (are you running qri in another terminal?)" if run while `qri connect` was running. This is due to the face that the repo and ipfs are locked so that only only process touches that at once. The Repo() method on
cmd/factory.go Factory would therefore fail with this error. However, body doesn't actually need to directly touch the repo, and can be run over RPC like other commands. Setup will fail anyway because the repo already exists.
Only `qri export` is now using the Repo() method, we should stop doing that and then remove Repo() if possible.
=> fix(cmd): Both body and setup runnable during "qri connect"

actions/list_datasets.go, actions/list_datasets_test.go
Before, running `qri list not_found` would try to deref a nil error value, leading to a crash. Instead, check if the returned profile pointer is null and print an appropriate error.
=> fix(list): Listing a non-existant profile should not crash

actions/dataset.go, actions/dataset_test.go, api/datasets.go, cmd/cmd_test.go, cmd/remove.go, cmd/remove_test.go, cmd/testdata/movies/body_thirty.csv, lib/datasets.go, lib/datasets_test.go, lib/params.go, rev/rev.go, rev/rev_test.go
New flag --revisions is now required by remove. If set to an integer greater than zero, will remove that many revisions, starting from newest. If set to "all", will remove the dataset entirely (the old behavior).
=> fix(remove): Remove requires the --revisions to specify what to delete

cmd/connect.go, cmd/export.go, cmd/factory.go, cmd/factory_test.go, cmd/qri.go, cmd/render_test.go, lib/export.go, lib/lib.go, lib/lib_test.go, lib/params.go
Move the main functionality of export down to lib/. Invoke the RPC call if needed. Remove the Repo method from Factory, and make the Node method more explicit (only `qri connect` needs it). Now all commands can be run while connected.
Fixes https://github.com/qri-io/qri/issues/661.
=> fix(export): Export can be used while running `qri connect`

cmd/export.go, cmd/qri.go, config/store.go
depends on qri-io/cafs#21.
This adds a new "Options" object to store configuration, which after recent upgrades to github.com/qri-io/cafs/ipfs, supports configuring qri's IPFS node to enable the IPFS HTTP API and optionally support for pubsub.
To enable both, config.yaml's `store` should now look like this:
```yaml
store:
type: "ipfs"
options:
api: true
pubsub: true
```
if `store.options.api` is set to `true` it will use the IPFS config to figure out what address to bind the api to (in ipfs that defaults to localhost:5001).
with both api and pubsub activated, it's possible to talk to the underlying pubsub api by supplying an `--api` flag to the go-ipfs binary (version 0.4.18 or higher):
1. run `qri connect` in a terminal 
2. in another terminal: `ipfs --api /ip4/127.0.0.1/tcp/5001/ pubsub …
=> feat: Ipfs api

actions/dataset.go, actions/dataset_test.go
The old error message was "invalid dataset: structure is required", coming from https://github.com/qri-io/dataset/blob/bd4df7ad41d13b78a6ce1ed786e112319dbba210/validate/dataset.go#L33. This one more accurately describes what's going on.
=> fix(save): Improve error message if new ds has no body or structure

README.md
Current contributor link in the heading of README goes to a 404 page, this fixes it
=> docs: Change contributor link

actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, api/datasets.go, base/base_test.go, base/dataset.go, base/dataset_test.go, cmd/save.go, lib/datasets.go, lib/datasets_test.go, lib/lib_test.go, p2p/log_diff_test.go, p2p/log_test.go, repo/test/test_repo.go
adds a new option to `lib.DatasetRequests().Save()` that forces new commit creation even if `no meaningful changes` are detected.
=> feat(lib.Datasets.Save): add force flag to skip empty-commit checking

base/entries.go, base/entries_test.go, base/render.go, cmd/cmd_test.go, cmd/export.go, lib/datasets_test.go, lib/export.go
Many changes to the export command to get it working more closely in line with the recent rfc https://github.com/qri-io/rfcs/blob/master/text/0021-export_behavior.md.
Changes include:
* Export as a single file yaml
* Respect `use` when exporting
* Derive the filename when -o flag isn't used, using the repo name and timestamp
* Derive the format if -o is used, by looking at the file extension
* Calculate absolute path for where export should write, without uglyfying console output
* Introduce new base.ReadEntries utility for turning EntryReader into body
* Switch default export format to single file json
Some things that are broken now, to be fixed later:
* --zipped is broken for now
* Raw block "native" export format
* Needs tests
=> fix(export): Overhaul export command

base/fill_struct.go, base/fill_struct_test.go, cmd/cmd_test.go, cmd/list.go, cmd/save.go, cmd/save_test.go, cmd/testdata/movies/meta_override.yaml, lib/datasets.go, lib/datasets_test.go, lib/file.go
Add a custom routine FillStruct for deserialization. This will used for parsing dataset json and yaml files when saving. This solves 4 problems:
* Field names are now case insensitive
* Unknown field names (such as misspellings) are now an error
* That is, unless the target struct is able to store arbitrary fields (Meta)
* Allow for saving individual components, by checking the "qri" field
=> feat(fill_struct): Json and yaml deserialization rewrite

base/fill/struct.go, base/fill/struct_test.go, config/config.go, config/config_test.go, config/testdata/default.yaml, lib/config.go, lib/file.go
Now fill.Struct is in base/fill/struct.go. Restore the config.ReadFromFile function, originally deleted by a2efbf30e35. Fix config/testdata/deafult.yaml which had invalid field names that were not being caught by old tests.
=> refactor(fill): Move base/FillStruct to base/fill/Struct

actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, api/datasets.go, base/base_test.go, base/dag.go, base/dataset.go, base/dataset_test.go, cmd/dag.go, cmd/dag_test.go, cmd/get.go, cmd/save.go, cmd/save_test.go, cmd/testdata/movies/dataset_with_viz.json, lib/datasets.go, lib/lib_test.go, p2p/log_diff_test.go, p2p/log_test.go, repo/test/test_repo.go, rev/rev.go, rev/rev_test.go
1) Adds 'rd' as a label to dag.Info
2) Adds 'rendered' and 'rd' as options to `qri dag info [label]`
3) Adds 'rendered' as an option to `qri get`
4) Adds `no-render` flag to `qri save`, to not save a rendered visualization with the dataset
5) Adds `shouldRender` flag to `lib.Save`, `actions.SaveDataset`, and `base.CreateDataset`
6) Updates tests!
need to close qri-io/dataset#181
=> feat(dag.Info, cmd/save, cmd/get): adjusts qri command line to work with the rendered visualization

base/fill/path_value.go, base/fill/path_value_test.go, cmd/config.go, config/config.go, config/config_test.go, config/remotes.go, lib/datasets_test.go, lib/remote.go
Instead of the old Config.Set, use the new base/fill/PathValue to Set and Get dot-separated field values on the Config object. Use this to set and get Remote names.
=> feat(remotes): base/fill/PathValue used by Config, to enable Remotes

cmd/save.go, lib/export.go, lib/file.go, lib/file_test.go, lib/testdata/component_files/commit.yaml, lib/testdata/component_files/meta.json, lib/testdata/component_files/meta.yaml, lib/testdata/component_files/structure.json, lib/testdata/component_files/structure.yaml
AbsPath is a filesystem concern, and belongs in the qfs package. This moves it (and properly documents the lib API break, a habit we need to improve on a bit)
Plus small bump to test coverage for lib.ReadDatasetFiles
=> replace lib.AbsPath -> qfs.AbsPath, add lib.File tests

base/render.go
I was running into issues adding templates to existing datasets that for some reason didn't have `format: "html"`. This tiny hack fixes that for now
=> fix(render): supply default 'html' format if none exists

actions/dag.go, actions/dataset.go, api/api.go, api/webapp.go, lib/remote.go, p2p/bootstrap.go, p2p/node.go, p2p/peers.go
Instead of passing around IPFSNode pointers everywhere, add an accessor that directly returns a CoreAPI pointer, and an IPFSNamesys pointer. Simplifies a bunch of call sites. Fixes #720.
=> refactor(p2p): Give node a CoreAPI accessor to simplify dependencies

actions/list_datasets.go, base/dataset.go, lib/profile.go, repo/ref.go, repo/ref_test.go
Handle peername changes all the time, by matching profileID, instead of only doing so if a third parameter was being supplied to CanonicalizeProfile.
=> fix(ref): CanonicalizeProfile just handles renames all the time

actions/remote.go, actions/remote_test.go, config/api.go, lib/remote.go
Add methods to actions/remote.go that represent the steps of pushing to a remote using dsync. Implement the timeout for dsync sessions. Add tests.
=> refactor(remote): Split remote push into mulitple actions. Add timeout.

actions/list_datasets.go, actions/list_datasets_test.go, base/dataset.go, base/dataset_test.go, cmd/list.go, lib/datasets.go, lib/params.go, p2p/datasets.go
Calling `qri list [term]` will list only datasets that have the substring "term" in their name. To list another peer's datasets, use the flag --peer.
=> fix(list): qri list new command-line interface

Makefile
I have no idea why, but CI is now failing without this dependency, I'm guessing some upstream package changed their deps. go modules would be nice
=> chore(makefile): add missing text package dep

api/api.go, api/profile.go, cmd/config.go, cmd/factory.go, cmd/factory_test.go, cmd/get.go, cmd/publish.go, cmd/qri.go, cmd/remove.go, lib/config.go, lib/lib.go, lib/profile.go
We've talked a bit about this internally, but we have a new guideline for when something should be an interface: if we can think of more then one implementation... it should be an interface!
Otherwise, let's just make it a concrete struct! 
Our first move over to this philosophy is the `lib.ConfigMethods`. Because we need to serve Qri over RPC, we need to follow some rules about the signatures of the methods we are registering. One of the stipulations for registering a method over rpc, is the struct on which the method operates must be exported. Because we implemented a private `configMethods` struct, that satisfies the `ConfigMethods` interface, we would need to jump through a few hoops to get the `configMethods` struct to be seen as exported when we try registering its methods over RPC. …
=> refactor(lib.ConfigMethods): removes `lib.ConfigMethods` interface

base/fill/error_collector.go, base/fill/path_value.go, base/fill/path_value_test.go, base/fill/struct.go, base/fill/struct_test.go, config/config_test.go
Primary change: the path that an error occurs at is now prepended to the error message. Now they look like "at Meta.Title: need string, got int". Introduce FieldError, for when a field cannot be converted from its given type to the target type. Introduce ErrorCollector, which collects errors and merges them.
Raise test coverage by a significant amount.
=> feat(base/fill): Overhaul error handling

repo/ref.go, repo/ref_test.go
When CanonicalizeDatasetRef sees a ref with a matching profileID, but a different peername, use that new peername. The profileID is considered reliable, while the peername can change due to a peer rename. It should not be an error to see a different peername.
=> fix(canonicalize): Correct peername when profileID matches

lib/lib.go
If loading the config has an error (for example: it contains an unknown field), the OptLoadConfigFile function needs to return an error, otherwise later Options will have a nil pointer for the config, causing them to segfault.
=> fix(config): Check err when parsing config to avoid segfault

cmd/cmd_test.go, cmd/testdata/movies/tf_123.star
Depends upon https://github.com/qri-io/dsdiff/pull/16 and https://github.com/qri-io/qri/pull/754. Currently `save`ing with a transform that produces no changes is broken, it always creates a commit because the differ see a new transform.ScriptPath. This fixes that.
=> test(transform): Detect when transforms don't produce any changes

actions/dataset.go, actions/transform.go, actions/transform_test.go, cmd/cmd_test.go, cmd/testdata/movies/body_two.json, cmd/testdata/movies/tf_add_one.star, lib/config.go
Pass prev dataset as well as next dataset, in order to support new get_body functionality added by https://github.com/qri-io/startf/pull/41.
=> fix(transform): Pass prev dataset to ExecScript

cmd/add.go, cmd/diff.go, cmd/diff_test.go, cmd/get.go, cmd/list.go, cmd/log.go, cmd/peers.go, cmd/print.go, cmd/print_test.go, cmd/registry.go, cmd/search.go, cmd/search_test.go, cmd/stringers.go, cmd/stringers_test.go, cmd/update.go, repo/test/test_repo.go
While embarking on the previous `page` and `pageSize` journey, we found a fun env variable: `PAGER`, by checking if `PAGER` is set, or by defaulting to `more`, we can send users to a pager for large outputs, typically lists. (If `PAGER` isn't set, and if `more` or `less` isn't valid on the user's system, we default to outputting the text to the terminal)
This refactor also unifies our output, especially for lists. It uses the`fmt.Stringer` interface to leverage one function, `printItems`, that formats lists/numbering items.
Each kind of struct that we wish to output (so far, `config.ProfilePod` and `repo.DatasetRef`) is aliased (to `peerStringer`, `refStringer`, and `logStringer`), and given a new `String` method that formats each struct the way we want for that particular usage. So we …
=> feat(pager): to make it easier to read, long output on the cli is sent to a pager

api/datasets.go, api/datasets_test.go, update/cron/job.go
closes #766
This refactor also separates out the part of the bodyHandler that just converts the request params to GetParams, and puts it into a `makeBodyGetParams` func (plz feedback on name). This allows us to test the bodyHandler easier. Added `TestMakeGetBodyParams` which does just that.
This also fixes a linting bug in update/cron/job
=> refactor(api/body): add limit and offset params to api /body endpoint

api/update_test.go, cmd/qri.go, cmd/update_test.go, lib/lib.go, lib/lib_test.go, lib/update.go, lib/update_test.go, repo/repo.go, repo/repo_test.go, update/cron/cron.go, update/cron/file_job_store.go, update/daemon.go, update/daemon_darwin.go, update/update.go
This PR closes #765 by requiring a `repoPath` param to `lib.NewInstance`.
I've also reorganized the structure of the `update` service in a qri repo. all update stuff except `/bin` is moved into an `update` subdir. files are relabelled.
before:
```
.qri
├── bin
│   └── qri
├── config.yaml
├── cron_jobs.qfb
├── cron_logs.qfb
├── ds_refs.json
├── events.json
├── index.bleve
│   ├── index_meta.json
│   └── store
│       └── ...
├── logs
│   ├── 1557256003-test_count.log
│   ├── 1557773521-country_codes.log
│   ├── 1557773581-test.sh.log
│   ├── ...
│   ├── stderr.log
│   └── stdout.log
├── peers.json
├── peers.json.lock
├── root
└── selected_refs.json
```
after:
```
.qri
├── config.yaml
├── ds_refs.json
├── events.json
├── index.bleve
│   ├── index_meta.json
│   └── store
│       └── ...
├── …
```
=> Organize repo

api/update_test.go, cmd/qri.go, cmd/update_test.go, lib/config_test.go, lib/lib.go, lib/lib_test.go, lib/update_test.go, repo/repo.go, repo/repo_test.go
@dustmop put forth the view that default path negotiation should be the concern of cmd. Sound right to me, which implies that lib.NewInstance should require a path, and cmd should do the work of deciding between flags, $QRI_PATH, and the default repo location, passing that off to lib. Thankfully we already to do this with our cmd.PathFactory interface, and have a hot-swappable version for testing. This commit removes the recently-introduced repo.Path method, and does some minor cleanup.
While we're playing with the signature of NewInstance, it makes sense to also require a context.
library consumers should always be providing a context to the instance constructor, even if just
context.Background(). Adding this requirement signals to the user that they should first understand how context …
=> refactor lib.NewInstance to require context and a repo path. make cmd the owner of default repo path.

actions/dataset_test.go, actions/testdata/now_tf/input.dataset.json, cmd/stringers.go, cmd/update.go, lib/diff_test.go, lib/testdata/now_tf/input.dataset.json, lib/update.go, update/cron/cron.fbs, update/cron/cron_fbs/Job.go, update/cron/job.go, update/cron/job_test.go, update/update.go
This is a somewhat advanced use-case, but one that I'd like to address for my own qri needs (I maintain a number of qri repos on my machine). running:
```
qri update schedule --use-repo /path/to/other/repo user/dataset R/PT1W
```
will store a "repoPath" value along with the job, run qri update with that repo, which will cause updates to be written and stored in that repo, while running against the same daemonized update process. Basically: 1 update process, lots of repos.
I'm calling this an experiment b/c it most definitely relies on not moving your repo directories once updates are scheduled, and I haven't written a test or throught carefully about what error to show if that repo dir moves. Other than that, I've got it working locally & it's delightful.
I'm also keeping it off the API …
=> experimental support for multi-repo updates with --use-repo

config/api.go, config/api_test.go
we missed a few fields in `config.API.Copy()` that's causing `qri connect --setup` to not allow serving remote traffic, because `cmd`'s `Connect` uses a copy of the api config ☹️
=> fix(config): fix api.Copy not copying all fields

cmd/list.go, cmd/log.go, cmd/peers.go, cmd/print.go, cmd/search.go, cmd/update.go
this now starts counting at 25:
```
$ qri list --page 2
```
=> fix(cmd): listing page 2 starts numbering at the offset

Makefile, cmd/dag.go, cmd/print.go, cmd/print_test.go, cmd/search_test.go, cmd/stringers.go, cmd/stringers_test.go, cmd/update.go, update/update.go
should address the "usability tested" checklist item in #763
Best to test this one by pulling the branch & building, then playing with update commands. Ideally the output makes things understandable. The less mental gymnastics, the better.
I've switched our human-formatting stuff to a package because we went from needing just one kind of "human" output (file sizes), to a few (relative dates, etc). `github.com/dustin/go-humanize` seems to fit the bill nicely.
=> Cleanup update output

api/webapp.go, cmd/cmd_test.go, cmd/stringers.go, cmd/stringers_test.go, cmd/update.go, cmd/update_test.go, lib/datasets.go, lib/update.go
fix some UX issues around update, make `qri update run` actually work. These changes can/should be better tested, but like, deadlines.
=> fix: update cleanup with better CLI output

cmd/stringers.go, cmd/stringers_test.go, lib/update_test.go, update/cron/cron.fbs, update/cron/cron.go, update/cron/cron_fbs/Job.go, update/cron/cron_test.go, update/cron/http_test.go, update/cron/job.go, update/cron/job_store_test.go, update/cron/job_test.go, update/cron/jobs.go, update/update.go
builds on #787, let's review & merge that one first.
After playing with cron for a bit myself, the UX of 'qri update log' needs a little work. I've added a RunNumber field to job that increments with each execution, which will allow us to bring cron into line with it's CI/github issue-inspired workflow. I do keep a rough tally of CI run numbers in my head (generally rounded to the second-largest 10's column), and look forward to having this hueristic in Qri update jobs.
I've also taken this last chance before we ship a release to refactor the field names of our job flatbuffer. This is a very permanent API, so the more right we can get things before release, the better. In this case I changed fields like "lastRunStart" to just "runStart", which more accurately depicts what state the field …
=> feat(cron): add incrementing job number, refactor job names

go.sum, lib/lib.go, lib/lib_test.go, lib/setup.go
need to load plugins before attempting to configure IPFS, flatfs is
specified as part of the default IPFS configuration, but all flatfs
code is loaded as a plugin.  ¯\_(ツ)_/¯
This works without anything present in the /.ipfs/plugins/ directory b/c the default plugin set is complied into go-ipfs (and subsequently, the qri binary) by default
Our tests missed this because the test suite needs to load all plugins to run
tests in the first place. This is going to be particularly tough to test.
We'll need to either:
* figure out a way to cleanly unload all plugins in IPFS
* use an "external" test of some sort
We should do some research into plugin unloading, we could also consider using a higher level package to test the "final" setup behaviour, which may not call plugin loading at …
=> fix(setup): load plugins before attempting to setup IPFS

base/render.go
this includes a copy-paste from the lower-level qri-io/dataset/dsviz outline comment. I couldn't find a nice place to put it, so I've added the comment inline, in `qri-io/qri/base.Render`
=> docs(viz): add outline comment for HTML viz templating

api/webapp.go, cmd/connect.go, cmd/connect_test.go, config/config.go
two funky things were happening when trying set up the `FrontendHandler`
1) `s.resolveWebappPath` was running in a go routine. The `webappEntrypointHash` that was being passed to the `/webapp` handler was therefore old! When the frontend webapp went to make certain requests, such as lazy loading parts of the app, it was being redirected to an incorrect endpoint.
2) the new webapp path was not being saved to the config! This means everytime we `qri connect`, the webapp was being 'updated'
This refactor removes the go routine and saves the new webapp path correctly!
It also adds some logging to the FrontendHandler, noting when we are fetching off the distributed web.
This pr also removes all the ephemeral `qri connect` flags
=> fix(webapp): must resolve path before passing path to frontend webapp handler

api/webapp.go
When a user runs `qri connect`, we should 1) checking to see if the current webapp is out of data, 2) trying to fetch and pin a new webapp 3) have the frontend handler send back a temporary script if the webapp has not finished updating 4) send the correct script once it has updated.
This commit creates a go routine that checks is the webapp has updated, and tries to fetch and pin that updated website. This go routine communicates on a channel, to update a `updating` bool. The handler uses this `updating` var to determine if it should send back the temporary script, or the actual webapp.
=> fix(webapp loading):  update, fetch, and pin webapp on `qri connect` 

.circleci/config.yml
See https://github.com/dgraph-io/badger/issues/886#issuecomment-505500955 for more context.
=> chore(ci): Fix dgraph-io badger issue.

cmd/publish.go, cmd/update.go
Capitalizes the short command for `publish` and other commands that were not capitalized
=> docs: capitalize short description of 'qri publish' and other commands

actions/actions_test.go, actions/dataset.go, actions/dataset_test.go, cmd/save.go, cmd/status.go, fsi/status.go, go.mod, go.sum, lib/datasets.go, lib/lib_test.go
First, we now check status mapping in _both_ directions, which means we can report removed components as well as added ones. There are some idiosyncrasies here that I think we need to introduce terminology to describe. Yay Spec(ish) time!
There are components of a dataset who's existence or lack thereof is "bound" to some other factor. Our document model enforces these restrictions to keep datasets working properly. Immediate examples: 
* the `structure` component is bound to the existence of a body. If a body exists, structure MUST exist. if a body doesn't exist, structure MAY exist.
* `commit` is bound to a dataset version existing. if a dataset version exists, it MUST have a commit component.
* the `dataset` itself is bound to any component existing it's not possible to not have a …
=> feat(replace-save,removed-status): report removed components in qri status, replace-save support

cmd/cmd_test.go, cmd/export.go
closes #842
stdout printing from tests is irritating. this sends it to output buffer. Also fixes the output of the export command
=> test(cmd): route output to buffer for cleaner test output

cmd/fsi_test.go, cmd/ref_select.go, cmd/ref_select_test.go, cmd/validate.go, cmd/validate_test.go, fsi/status.go, lib/datasets.go, lib/datasets_test.go
Validate can be run in an FSI directory, using the schema and body in the working directory. Change how linked dataset UI is printed. Turn the underscore in parse_error into a space.
=> fix(validate): Validate works with FSI. Various FSI cleanups.

api/datasets.go, api/remote.go, api/root.go, cmd/publish.go, lib/datasets.go, lib/remote.go, remote/client.go, remote/remote.go
builds on #882. I'll rebase once it's merged. API isn't properly returning publication status when getting single datasets, which is now important for publish status tracking.
=> fix(api): report publish status when fetching a single dataset

remote/client.go, remote/remote.go
remote request meta was conflating the profileID of the _requesting user_ with the profile id of the _dataset owner_. These might be different.
=> fix(remote): add requesting profile ID to remote hook signature

config/registry.go, config/repo.go
closes #898.
Also makes `https://registry.qri.cloud` the new default.
=> fix(config): enable setting config over RPC

api/fsi.go
A follow-up to https://github.com/qri-io/qri/pull/913, add the mkdir parameter to the api for init.
=> feat(fsi): Api can set directory to create for init

actions/dataset.go, api/api.go, base/dataset.go, go.mod, go.sum, lib/lib.go, p2p/node.go, remote/client.go
closes #916.
if we have an IPFS node instance, `node.GoOnline` has to make a new instance to connect properly. If `remoteClient` retains the reference to the old instance, we run into issues where the online instance can't "see" the additions. We fix that by re-initializing the client with the new
instance.
Debugging this one was not fun.
=> fix(add): need to re-initialize add when connecting

base/dataset.go, cmd/stringers.go, repo/ref.go
DatasetRef grows again. The next phase of changes for Qri require a refrence be able to model the state of not being in the local qri repo. This lands support for such a change while also fixing `qri list`, which currently chokes on a foreign reference.
=> refactor(DatasetRef): add Foreign flag to dataset reference, show in qri list

api/api.go, api/fsi.go, api/fsi_test.go, lib/fsi.go, lib/fsi_test.go
closes #935.
hooked up an API endpoint. this'll let qri desktop edit metadata. In the end I don't think it makes sense to overload the `/save` endpoint quite yet. We'll need more work before these paths properly overlay. So let's use `POST /fsi/write` for now instead, sending a JSON representation of a dataset.
=> feat(fsi): add fsimethods.Write to write directly to the linked filesystem

api/datasets.go, cmd/add.go, lib/datasets.go, lib/datasets_test.go
closes #940
This allows adding a dataset & linking it to a directory in the same command. you can now pass `dir` as a query param to `POST /add/[name]/dataset` and provide a filepath
=> feat(add): add link flag to lib.Add, CLI, API

cmd/search.go, cmd/search_test.go, cmd/stringers.go, lib/search.go, lib/search_test.go, registry/regclient/search.go, registry/search.go
putting in some work on #943, #908
Search is kinda gorked right now and should get a fix before we cut a release. This cleans up responses & brings us in line with the new search API response structure. For now we've moved to standard dataset responses only as search results. This defines a new search result stringer and makes room for a registry URL link.
=> fix(search): update to new registry api search result format

actions/recall.go, api/datasets.go, base/revisions.go, base/revisions_test.go, cmd/remove.go, cmd/remove_test.go, dsref/info.go, dsref/ref.go, dsref/ref_test.go, dsref/rev.go, dsref/rev_test.go, go.sum, lib/datasets.go, lib/datasets_test.go, repo/ref.go, repo/ref_test.go
we need a place for housing both parsing & parsed dataset references. Other code needs this refactoring to sort out import cycles
=> refactor(dsref): rename rev package to dsref, a home for all ref string parsing

remote/client.go, remote/remote.go, remote/signature.go, remote/signature_test.go
This pr renames `RemoveDatasetRef` to `RemoveDataset`. It calls on `base.RemoveNVersionsFromStore` to remove the blocks from the filestore, and uses `repo.DeleteRef` to remove the dataset reference from the repo
`RemoveDataset` calls the `datasetRemovePreCheck` function, if it exists, before it removes the dataset and its history.
`RemoveDataset` calls the `datasetRemoved` function, if it exists, after it removes the datasets and its history
This pr also moves all signature logic to a new `signature.go` file.
It adds a `VerifySigParams` that takes a publicKey, a `params` `map[string]string`, and returns a bool, error. Bool is true if the signature is verified. Basically the inverse of the `sigParams` func.
When remotes have their own keystore, we should make `VerifySigParams` private.
=> fix(remote): `DeleteDataset` func will now delete an entire dataset's history

go.mod, logbook/oplog/log.go, logbook/oplog/log_test.go
We're going to use this `ID` thing in a bunch of places. While we're here I'd like to avoid some of the headaches caused by base64, switching to base32 encoding for id bytes for a few reasons:
* base64 uses the "/" character, which messes with paths
* can be used as URLS
* doesn't rely on case, which means it works in case-insensitive contexts
* lowercase is easier on the eyes
This builds on a number of hard lessons learned in the IPFS community.
=> refactor(logbook): rename InitOpHash to ID, use lower-base32

base/log.go, base/ref.go, cmd/cmd_test.go, cmd/fetch_test.go, cmd/fsi_integration_test.go, cmd/log_test.go, cmd/stringers.go, fsi/init.go, identity/identity.go, identity/identity_test.go, lib/datasets_test.go, lib/log.go, lib/log_test.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/http.go, logbook/logsync/http_test.go, logbook/logsync/logsync.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p.go, logbook/logsync/p2p_test.go, logbook/oplog/log.fbs, logbook/oplog/log.go, logbook/oplog/log_bench_test.go, logbook/oplog/log_test.go, logbook/oplog/logfb/Operation.go, remote/remote.go
closes #997
This PR lands a few key changes to logbooks:
* arranges logs into a cleaner hierarchy of user >> dataset >> branch, removing the top level arrange-by-model variation
* disambiguates what is written to each branch. User logs only contain operations that affect the user model, Dataset logs only contain operations that affect entire datasets, and Branch logs only contain operations for a line of commit activity
* introduces methods for fetching by _ head reference_ using names, and ID, using a log identifier
* renames "name" model to "dataset", so we now have `user`, `dataset`, and `branch` models
* renames `WriteNameInit` methods to match dataset business logic conventions. Now called: `WriteDatasetInit`, `WriteDatasetRename`, and `WriteDatasetDelete`
* adds logic to track oplog …
=> refactor(logbook): working identifers into logbook

base/dataset.go, go.mod
this is a bit of a stop-gap for now, but users are seeing bad errors when dataset histories aren't fully persisted & they attempt to delete. This may end up causing stray-pinning, and the long-term solution for that is to use logbook for this remove task. We can also use logbook to identify stray pins & reclaim the space
closes #989
=> fix(remove): don't fail if remove encounters an issue traversing qfs history

base/component/component.go, base/component/kinds.go, cmd/fsi_integration_test.go, cmd/log_integration_test.go, fsi/fsi.go, fsi/fsi_test.go, fsi/init.go, fsi/mapping.go, fsi/status_test.go, lib/fsi.go
If init has errors, simply bailing with an error isn't good enough. It can leave our repo and working directory in unusable states. Instead, we create a cleanup function that will undo work done so far, calling any cleanup function that already exists.
Convert fsi_integration_test to new, simpler TestRunner methods.
=> fix(init): If init has errors, rollback changes

base/component/component.go, base/component/kinds.go, base/component/list_dir.go, fsi/status.go, go.mod, go.sum
This is is a short stand-in for full-fledged support. FSI will _probably_ throw a fit if we tried to add configuration to a transform via a `dataset` file in FSI, and declared a `transform.star` file. But the upside, THIS ADDS TRANSFORMS VIA FSI
=> feat(fsi transform): skeletal support for transform scripts via FSI

base/log.go, base/log_test.go, identity/identity.go, lib/datasets_test.go, lib/lib.go, lib/log.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/http.go, logbook/logsync/http_test.go, logbook/logsync/logsync.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p.go, logbook/logsync/p2p_test.go, logbook/oplog/log.fbs, logbook/oplog/log.go, logbook/oplog/log_bench_test.go, logbook/oplog/log_test.go, remote/remote.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/mem_repo.go, stats/cache.go
when initially implementing logbook, I'd intented for oplog to be a "thicker" API that had a strong notion of authorship. In practice the details of author attribution have happened at the logbook layer as as part of declarative method names. This refactor makes that change explicit, removing private key and author details from oplog.
I've also taken this chance to move the author stuff into the identity package, where it belongs. I'm sure the name "Author" will be refactored over time, but at least it's in the right place.
=> refactor(oplog): Logstore interface

cmd/add.go, cmd/remove_integration_test.go, lib/datasets.go, remote/mock_client.go
When removing a dataset, ignore logbook "not found" errors, since we're removing the dataset anyway, it doesn't matter if something is missing. Fmt the mock_client added in the previous PR.
=> fix(remove): Remove works on foreign datasets, even if logbook missing

cmd/checkout.go, cmd/diff.go, cmd/export.go, cmd/fsi.go, cmd/fsi_integration_test.go, cmd/get.go, cmd/list.go, cmd/log.go, cmd/ref_select.go, cmd/ref_select_test.go, cmd/remove.go, cmd/render.go, cmd/restore.go, cmd/save.go, cmd/status.go, cmd/test_runner.go, cmd/validate.go, fsi/fsi.go, fsi/fsi_test.go, lib/datasets.go, lib/fsi.go, lib/params.go, repo/ref.go
Whenever the user manually moves or deletes a working directory, we get into a situation where the fsiPath in the qri repo is now out of date with the .qri-ref (or lack thereof) in that working directory. We should detect this situation as best we can. For now, if the user runs another command in the folder's new location, use that opportunity to update the fsiPath. Or, if the user runs `qri list`, check the folders in the repo's references to make sure everything is still properly linked. In the future, we can watch the file system to make this process more reliable. But for now, this establishes the .qri-ref linkfile as the primary source of truth.
Fixes https://github.com/qri-io/qri/issues/938 and https://github.com/qri-io/qri/issues/890
=> fix(fsi): When working directory is moved or deleted, update FSI Path

cmd/setup.go, cmd/setup_test.go
We need to create a doggo nickname during the release process, in order to name the release. It takes a bit of effort to do so (make a temporary directory, set environment variables, run `qri setup`, cleanup the temp), so this makes it easier by removing some steps.
=> feat(doggo): Setup flag that only creates a nick and displays it

base/validate.go, base/validate_test.go, cmd/cmd.go, cmd/save_test.go, cmd/testdata/movies/schema_only.json, cmd/validate.go, cmd/validate_test.go, lib/datasets.go, lib/datasets_test.go, lib/lib_test.go
FSI broke validate because we switched from schema.json back to structure.json. The old functionality was looking specifically for schema.json (in the cmd package, no less) and did not survive this change. Instead, we should use the FSI package which correctly finds relevant component files.
Cleanup the lower levels of how validate works. Before, it was converting things back and forth, between cmd -> lib -> base -> dataset -> jsonschema. No need to do all of that unnecessary work.
=> fix(validate): Improve validate so it works with FSI

cmd/qri.go, fsi/fsi.go, lib/datasets.go, lib/fsi.go, lib/lib.go
The --log-all flag can be used by Desktop to log more information to the default file we create at startup. Add logging to lib.Get errors and fsi.Checkout so we can check errors that occur in the wild.
=> fix(log): Add --log-all flag to enable logging everywhere

logbook/logbook.go, logbook/oplog/log.go, logbook/oplog/log_test.go
ensures parent property is set correctly
=> fix(logbook): use AddChild instead of directly appending to oplog.Log.Logs

api/remote.go, api/websocket.go, base/hidden_file_windows.go, base/log.go, cmd/add.go, cmd/connect_test.go, cmd/factory_test.go, cmd/fetch.go, cmd/fetch_test.go, lib/datasets.go, lib/remote.go, logbook/logbook.go, logbook/logsync/http_test.go, logbook/logsync/logsync.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p_test.go, remote/client.go, remote/mock_client.go, remote/peer_sync_client.go, remote/remote_test.go
we need a way to fetch logs & _not_ persist them. This does that.
I've also added a --logs-only flag to add which brings back the old fetch behaviour of persisting logs on fetch. Long term I'd like to merge all log pulling into "qri log" (for ephemeral fetching) and "qri clone" (for persisted fetching)
=> feat(remote): ephemeral log fetching with remoteClient.FetchLogs

go.sum, lib/integration_test.go, logbook/oplog/log.go
follow up to #1082, which contains a build error 😢.
This test found a nasty bug that crops out of recent refactoring work. Logsync fetches were producing logs with multiple children that have the same ID. This is caused by the recent `AddChild` switch. To fix the issue, I've added a check in `oplog.AddChild` that does a miniature version of merging: checking for an ID match & using the log with more operations.
There's a better fix for this, but we have divergent behaviour between two implementations of oplog.Logstore that need to be reconciled first. One implementation fetches children, the other doesn't. This creates problems.
=> fix(logbook): addChild should not create duplicate children

dscache/convert.go, dscache/convert_test.go, dscache/logbook_temp_builder_test.go
Our repos may contain datasets that are in dsref but not in logbook. This can happen from datasets created before logbook was implemented, or due to deleting logbook (which was necessary to work around bugs for a little while), or from the registry not syncing logs yet. For now, such dsrefs should still be added to dscache, but this behavior will not be needed in the future once we move over to dscache all the time.
Also add some more tests for dscache building, which eliminates a few TODOs.
=> fix(dscache): Add refs in dsref that logbook is missing. More tests.

base/save.go, cmd/list.go, cmd/save_test.go, cmd/test_runner_test.go, dscache/build/from_repo.go, dscache/convert.go, dscache/dscache.go, dscache/dscache_test.go, dscache/logbook_temp_builder_test.go, dscache/mutator.go, lib/datasets.go, lib/lib.go, lib/params.go, logbook/action.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/logsync_test.go, repo/buildrepo/build.go, repo/fs/files.go, repo/fs/fs.go, repo/fs/fs_test.go, repo/mem_repo.go, repo/repo.go, repo/test/test_repo.go
Add a logbook.Action that describes a change to logbook when a save happens.
Add dscache.Update which receives an action, and modifies the dscache (by copying, since flatbuffers don't support mutation), and saves the result to the repo.
Change dscache constructor so that a non-null dscache is always returned, but it'll just be "empty" if there's nothing in the repo. That allows us to "save" since a filename within the repo should always exist.
Rename --via-dscache flag to --use-dscache.
Make an integration test that demonstrates using `list` to make a dscache, then `save` to update it.
=> feat(dscache): Dscache will get updated by save, if it exists in the repo

.circleci/config.yml
Trying to fix the `[build failed]` error. Inspired by this thread: https://github.com/influxdata/flux/issues/1179
=> test(circleci): Switch to 8 cpus for docker build on CI

cmd/registry.go, lib/registry.go
also added a stderr success printout. logging is still accessible if lib's logging level is debug
closes #1096
=> fix(cli): remove extraneous logging from `qri registry prove`

Dockerfile
This updates the Go version used as the base container for the main `Dockerfile`, to avoid an error wherein the container image build complains that the Go version must be at least `1.13`. Fixes and closes #1117.
=> Fix: Go version in Docker

api/datasets.go, api/fsi.go, api/root.go, base/ref_test.go, base/remove.go, dscache/convert_test.go, dscache/dscache_test.go, p2p/node_test.go, p2p/test/ipfs.go, p2p/test/p2ptest.go, remote/mock_client.go, remote/peer_sync_client_test.go, repo/profile/id.go, repo/profile/id_test.go, repo/store_test.go, repo/test/spec/test_refstore.go
There's a potential for bugs related to how we construct profileIDs. I've run into this bug a few times, and the issue is getting worse during the switch to dscache. This change will help to solve the problem going forward.
We use a few different types around profileIDs:
1) ipfs's peerID which is a string of bytes derived from cryptographic information
2) repo/profile.ID which is an alias of peerID, moved into our own namespace
3) a string of a base58 encoded profileID that starts with "Qm..."
The issue originates from the fact that all three are basically strings, but with different semantics. (1) and (2) are byte sequences with the same contents, but occassionally need conversion due to having different go types. (3) is a base58 encoded string, meaning it exists as different bytes in …
=> fix(profileID): Disambiguate profileID construction to avoid subtle bugs

api/api.go, api/render.go, lib/render.go, lib/render_test.go
This'll now work:
`curl -X POST -H "Content-Type: application/json" "http://localhost:2503/render" -d '{"readme": { "scriptBytes" : "IyBoZWxsbyB3b3JsZAo=" }}'`
=> feat(api): support for dynamic dataset readme rendering

api/websocket.go, dscache/dscache.go, event/event.go, event/event_test.go, fsi/fsi.go, fsi/fsi_test.go, fsi/status_test.go, lib/fsi.go, lib/lib.go, watchfs/watchfs.go, watchfs/watchfs_test.go
* Adds in a bunch of `event` package changes from #1133, including `Unsubscribe` and `Publisher` interface.
* Refactors `NewFSI` constructor to accept a publisher
* Refactors `watchfs` to use the subscribe pattern
=> refactor(event): wiring watchfs up to FSI events

cmd/list.go
This is a very superficial fix for the username not displaying on a call to `qri list` without providing specific peer as an argument. 
It is not perfect because `repo/store.go#CanonicalizeProfile` shows that it is also possible to refer to one's own datasets by using `me` as a magic peername.  So running `qri list --peer me` now still gives a weird (meme worthy) message: `me has no datasets`. If that also needs to be taken into account the rabbit hole starts to become pretty deep for a simple feedback message. 
I would say that it is not worth complexity and just return the message "found no datasets".
=> fix(cmd/list): show username with no datasets to list

cmd/fsi.go, cmd/fsi_test.go, cmd/ref_select.go
I was poking around at the fsi commands this morning while misusing Qri Desktop and noticed that the arguments felt a little under-documented. This just adds positional argument info to the usage string for `qri fsi link` and `qri fsi unlink` to make them slightly clearer.
I thought about adding a longer description with more info, but since these are low-level commands that don’t normally show up when you run `qri --help`, that didn’t really seem worthwhile.
=> Document CLI args for fsi commands

DEVELOPERS.md
The table of contents listed and linked to a non-existent section, which I removed here. This also fixes the anchor syntax for the "development setup" heading, which was causing funny rendering on some browsers.
=> docs(developer.md): fix section header links

DEVELOPERS.md
came up a few times in discussion on discord, might as well have a linkable header we can point to
=> docs(developer.md): add note about ulimit workaround

cmd/dag.go, cmd/dag_test.go
Make the usage docs and argument parsing a little clearer for the `qri dag` family of commands:
- Only hide the top level command, so `qri dag --help` actually lists the subcommands.
- List optional and required positional arguments in usage string.
- Mark required flags as required.
- Only parse a "label" style argument when it's actually applicable.
I'm not deeply familiar with any of these commands, so I didn't actually try to spruce up the description strings. I mainly just followed the logic to understand what arguments were required (and what those arguments should generally represent).
=> docs(cmd): improve CLI docs for `dag` commands

cmd/fsi.go
This is a follow-on to #1170. We merged that one a bit too hastily and the usage string implied that DATASET was optional, when it actually isn't.
The last bit of conversation (https://github.com/qri-io/qri/pull/1170#discussion_r391354964) implied we might want to change the functionality to make this optional, though, so feel free to throw out this PR if you just want to move straight ahead with that instead.
=> docs(cmd): DATASET is required in `fsi unlink`

cmd/export.go
The `qri export --blank` command is now redundant — the more modern path to accomplish a similar need is with `qri init`. (Per this discussion on Discord with @b5 and @dustmop: https://discordapp.com/channels/497052800778502152/571427701475377152/687690467394977822) This removes it.
=> feat(cmd): remove `--blank` option from `export`

base/component/kinds.go, cmd/fsi_integration_test.go
This should fix issue #1155 and I also took into consideration the suggestions of @dustmop to add an additional validation on the tests regarding the files' permission.
=> fix(base): permission for files generated on init

cmd/add.go, cmd/checkout.go, cmd/config.go, cmd/connect.go, cmd/diff.go, cmd/export.go, cmd/fetch.go, cmd/fsi.go, cmd/get.go, cmd/init.go, cmd/list.go, cmd/log.go, cmd/peers.go, cmd/publish.go, cmd/qri.go, cmd/registry.go, cmd/remove.go, cmd/rename.go, cmd/render.go, cmd/restore.go, cmd/save.go, cmd/search.go, cmd/setup.go, cmd/stats.go, cmd/status.go, cmd/update.go, cmd/use.go, cmd/validate.go, cmd/version.go
Add positional argument information to all commands and clean up the descriptions and examples a bit.
~This is only half the commands and *very* much needs a second pass (lots of things I learned or decided partway through), but posting it here for safekeeping and if anyone wants to review early.~
The descriptions and examples now follow some basic styles for consistency:
- No leading/trailing blank lines. (This is pretty arbitrary; I was mainly trying to make things consistent. We could make other choices about this.)
- Short descriptions are phrases, not complete sentences — they start with a lower-case letter and do not end with a period. (Also arbitrary; was trying to go with what seemed most common.)
- Long descriptions are full sentences and paragraphs. They start with a capital …
=> docs(cmd): add argument names to CLI help text

DEVELOPERS.md
Looking at the comments in #1198, I realized I never *documented* the style I followed when trying to make the CLI help docs more consistent in #1182. This adds guidelines to `DEVELOPERS.md` (I wasn’t sure there was a more appropriate location).
=> docs(developers): add styleguide for CLI help

cmd/registry.go
Needed to re-authenticate/bind myself as I nuked my repo. 
`qri registry prove` requires an email to be supplied on the remote end but had no way to pass it.
=> fix(cmd): added the email flag to 'registry prove' as it is required

base/save.go, cmd/cmd_test.go, cmd/save.go, cmd/save_test.go, cmd/test_runner_test.go, cmd/testdata/movies/tf_123.star, lib/datasets.go, repo/test/temp_repo.go, startf/transform.go, startf/transform_test.go
cleans up some crossed wires, adds the necessary methods to test `ErrOutput` within `cmd` package tests.
closes #1194
=> fix(startf): script print statements print to stderr

config/testdata/default.yaml, config/update.go
Oops! As per https://github.com/qri-io/qri/issues/1159, TestUpdateMethods is flaky, because it's using the same port as Websockets. I didn't realize when adding Websockets that 2506 was already in use. I am trying out changing the update port because it's probably easier for Desktop that way, since Desktop is currently hardcoding the Websockets port number but isn't using update at all.
This change will fix one of the two reasons why TestUpdateMethods is flaky, the other being `qri connect` being run by other tests.
=> fix(update): Change default port for update service

cmd/fetch_test.go, remote/remote.go
Rewrite the TestFetchCommand to fix a number of problems. No longer runs "qri connect". Doesn't use the 2503 port. No longer serves RPC and Websockets. Removes the 5 second wait. Actually inspects the output of `log` and `fetch` to validate that they're working, with stable timestamps. Should fix a number of flakey tests and overall run faster.
=> test(fetch): Rewrite fetch test. Don't run connect, test expectations.

cmd/fsi.go, cmd/fsi_integration_test.go, cmd/test_runner_test.go, dsref/parse.go, fsi/fsi.go, fsi/fsi_test.go, lib/datasets.go, lib/fsi.go, repo/ref/convert.go, repo/ref/convert_test.go
Fsi unlink command will delete the appropriate link file, regardless of how it is called. Better handle edge cases, like inconsistent folder state. Add lots of tests to cover all of the types of behavior fsi unlink has.
=> fix(unlink): Fsi unlink handles more edge-cases, acts more sane.

cmd/stringers.go, lib/search.go
Ensures `rpc` can serialize the response. A quick skim through the codebase, this should not be present anywhere else.
Related issue:
https://github.com/qri-io/qri/issues/1193
=> fix(search): change type from interface to dataset so rpc can serialize

cmd/qri.go, lib/peers.go
Fixes https://github.com/qri-io/qri/issues/1179
The issue was when running 'offline' we will neither trigger an RPC call nor do we pass the instance/Node along which always drops the request due to 'not being connected'. In reality we want to check against the instance created by the `qri` command if we're not going to query against a live `qri connect` session and execute an RPC call if there is. RPC always takes precedence vs command local execution.
=> fix(cmd): pass node when not making online request for peers

cmd/fsi_integration_test.go
This addresses these:
```
--- FAIL: TestGetPreviousVersionExplicitPath (0.33s)
panic: expected output to start with "saved:", got "" [recovered]
panic: expected output to start with "saved:", got ""
goroutine 5175 [running]:
testing.tRunner.func1.1(0x542e2a0, 0xc0513bbef0)
/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc050648900)
/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:944 +0x3f9
panic(0x542e2a0, 0xc0513bbef0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/qri-io/qri/cmd.parseRefFromSave(0x0, 0x0, 0x5704723, 0x3d)
/Users/arqu/dev/qri/qri/cmd/fsi_integration_test.go:1656 +0x142
github.com/qri-io/qri/cmd.TestGetPreviousVersionExplicitPath(0xc050648900) …
```
=> refactor(test): test requires stable output

lib/datasets.go
Fixes missing file name if structure file is provided instead of schema file and adds message of root cause error.
=> Fix #1245: Render error details when schema file can not be read

cmd/add.go, cmd/completion.go, cmd/export.go, cmd/qri.go, cmd/render.go, cmd/save.go, cmd/validate.go
Relevant to https://github.com/qri-io/qri/issues/1236
Took a mix of inspiration between `cobra` docs and `kubectl` handling of `zsh` support.
Currently it only handles registered commands and flags, no support for dataset name autocomplete just yet. 
The convoluted approach for `zsh` is due to `cobra` not supporting "advanced/custom" autocomplete functions and thus would not work for the future dataset name autocompletion (or similar scenarios like peers etc).
=> feat(cmd): added command to generate basic cmd autocompletion scripts

api/datasets.go, api/fsi.go, api/root.go, base/dataset_prepare.go, cmd/cmd_test.go, cmd/fsi_integration_test.go, cmd/get.go, cmd/get_test.go, cmd/list.go, cmd/save.go, dscache/dscache.go, lib/datasets.go, lib/datasets_test.go, resolver/loader/loader.go, resolver/mem_resolver.go, resolver/mem_resolver_test.go, resolver/resolver.go
New resolver interface looks up VersionInfo or dataset from references or initIDs. A high-level implementation called DatasetResolver ties together fsi and dscache and dsfs to be used from lib.
Add a flag for experimenting with using dscache for get. Add some comments that describe where the resolver interface will be used next, and talking about how the save path should change in the future. Fix some small TODOs by adding missing tests.
=> feat(dscache): Dscache can be used for get command

event/event.go
See https://tip.golang.org/doc/go1.8#mapiter
=> fix(watchfs): Methods need a mutex to avoid concurrent writes

base/component/field_id.go, cmd/completion.go, cmd/list.go, cmd/peers.go, lib/config.go
Continues https://github.com/qri-io/qri/issues/1236
Adds support for `config` args, `structure` args, `peers`,  `workdir` and some generic improvements to the completion scripts.
=> Autocomplete improvements

cmd/qri.go, config/test_config.go
Sprint board didn't update so I got started on https://github.com/qri-io/qri/issues/955
Wound up on the https://github.com/qri-io/ioes/commit/28794e5a4c834251ed7e0fde143fd3c99bb58db3 commit.
Once we cut the release on `ioes` I'll update the deps here and we can merge.
=> fix(cmd): tty should auto disable color

cmd/qri.go, cmd/setup.go
Initialization and error handling is pretty messy right now. Init can only be run once, but if it encounters an error, that error can very easily be swallowed. Instead, save the err and return it each time Init is called in the future. This allows both accessing the instance early (to assign colors) and also will properly display an error for commands run before setup, instead of having those commands segfault.
In NewQriCommand.PersistentPreRun, check the instance is non-nil before accessing the config.
Remove the call to `f.Init` at the end of Setup, because at that point, Init has already been run and the sync.Once will make calling it again a no-op.
=> fix(setup): Don't crash when running `qri setup`

go.mod
Originally bumped by f08363dbeec4ce904b1935bdd0179bc0e8b2ae76, reverted by 7a6d8aee0fd0c1c090226093cef0d86b7deeb24d. Will fix the flaky test TestDatasetPullPushDeleteFeedsPreviewHTTP, issue https://github.com/qri-io/qri/issues/1172.
=> chore(dag): Bump dag version again to fix flaky tests

base/archive/zip.go
this was an incomplete fix to https://github.com/qri-io/qri/issues/1161
while running qri connect we need to properly handle the context deadline for a missing viz by ignoring the error.
This is causing major issues for our users, so I've dropped to smoke-testing, and can confirm this change fixes export in qri desktop, particularly for the turnstile dataset @chriswhong's been publishing.
=> fix(export): handle ok-case of bad viz while connected

cmd/cmd_test.go, cmd/fsi_integration_test.go, cmd/save_test.go, cmd/test_runner_test.go, repo/buildrepo/build.go, repo/test/temp_repo.go
The TestRunner uses a TempRepo, which should pass the correct qri path, instead of the root path, when building the repo. This prevents two separate repos from being constructed in tests, cleaning up a bunch of subtle bugs that we were working around. Some test timestamps change because now some things that were constructed twice are now only constructed once.
=> fix(repo): Construct temp repo using correct path

api/datasets.go, base/dsfs/dataset.go, base/revisions.go, base/revisions_test.go, base/save.go, cmd/fsi_integration_test.go, cmd/save.go, cmd/save_test.go, lib/datasets.go, lib/datasets_test.go
I'm not sure this should be merged as-is (which is why I've skipped tests for the moment).
We're in a situation where a few versions of qri have been creating bad DAG structures, referencing blocks not stored within the created DAG. Thanks to save being a patch operation, and FSI-linked save not recognizing the viz component, qri presents no way to remove a bad viz component. This --drop flag at least lets us drop entire component for now upon save.
Example uses:
```
$ qri save --drop viz
$ qri save --file body.csv --drop rm
```
=> feat(save): add --drop flag to remove dataset components when saving

cmd/fsi_integration_test.go, cmd/init.go, cmd/log_test.go, cmd/save_test.go, cmd/stats_test.go, cmd/testdata/detect/meta.json, dscache/builder.go, dscache/dscache.go, fsi/init.go, lib/file.go, lib/file_test.go, lib/fsi.go, lib/testdata/detect/meta.json, logbook/logbook.go
* Init works while running `qri connect`, by taking Abspath of source-body-path
* Init checks if the working directory has conflicting files before prompting for user input
* Init can use source-body-path with the value "body.csv", instead of failing
* Init will create an entry in dscache if run with --use-dscache
* Fix the error message when structure.json already exists when init'ing
* Can save using known component filenames instead of keys
* Improve the log test to inspect logbook's state
Fixes https://github.com/qri-io/qri/issues/1298, and https://github.com/qri-io/qri/issues/1297, and https://github.com/qri-io/qri/issues/1206.
=> fix(init): Multiple fixes to init, save, dscache

cmd/init.go
Oops, I recently broke this because there are no tests for what stdout writes.
=> fix(init): Derive dataset name from directory base, not whole path

base/log_test.go, base/ref.go, base/remove.go, base/save.go, cmd/init.go, dscache/convert_test.go, fsi/init.go, lib/fsi.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/logsync_test.go, logbook/oplog/log.go, logbook/oplog/log_test.go, logbook/temp_builder.go, logbook/types.go, remote/remote.go, repo/test/test_repo.go
Change most logbook methods, especially the ones that add operations to the logs, so that they accept initIDs instead. This will make it much easier to transition away from the old refstore.
Add a helper method that looks up the initID given a ref; this makes it possible to work with base before dscache is done.
Extract the initName helper out of mutations; callers should instead either have an initID or create one by using WriteDatasetInit.
Create strongly typed structs for each log level - AuthorLog, DatasetLog, BranchLog - to aid in understanding logbook code. They aren't used everywhere, but it's a start.
Remove CronJob Model now that update is gone.
=> refactor(logbook): Most logbook methods take an initID, not ref

api/log.go, cmd/log.go
Using the `pull` flag lets the user pull the latest logs from the remote source. No `remote` flag and `remote=registry` both default to pulling from the registry. 
At the api and cmd levels, if the user has the `remote` flag set to "registry", skip searching locally and instead search the default registry. This does not make any changes to lib or lower, lib still expects an empty `remote` param to mean search the registry. Leaving it this way until we have a better understanding of what is expected in future commands.
closes #1328
=> refactor(log): `pull` flag skips local log search, & `remote=registry` is recognized

api/api.go, api/render.go, api/render_test.go, cmd/factory.go, cmd/factory_test.go, cmd/qri.go, cmd/render.go, cmd/render_test.go, lib/lib.go, lib/render.go, lib/render_test.go
our current plans have us keeping the `render` functionality around. This brings render up to pace.
Considering we'll remove `ExportRequests` with the PR that does the merging work, I think this PR closes #1235.
=> refactor(lib): rename RenderRequests -> RenderMethods, use an instance

base/dsfs/dataset_test.go, go.mod
Benchmarks for the save code path with an added deep dive on the validation side.
Special note: this chokes on my machine for the 1G datasets without the optimizations that will follow on this.
Also will have to update the dependencies before merging, but want to get this up as a launch pad for the following PRs
=> test(benchmark): added benchmarks for save/validate

base/fill/struct.go, base/fill/struct_test.go, config/api.go, config/cli.go, config/config.go, config/config_test.go, config/filesystem.go, config/filesystem_test.go, config/logging.go, config/migrate/migrate.go, config/p2p.go, config/profile.go, config/registry.go, config/remote.go, config/repo.go, config/rpc.go, config/stats.go, config/store.go, config/testdata/default.yaml, config/testdata/deprecated.yaml, config/testdata/invalid.yaml, config/testdata/simple.yaml, repo/buildrepo/build.go
The basis is:
- Non-existing config means default to all (same as it was)
- If specified it creates all the named individual stores
- Empty array means disable all
Changes based on https://github.com/qri-io/rfcs/blob/master/text/0029-config_revision.md#remove-stale-configuration-fields
Addressing item No3 from #1346
Migration also needs to be implemented once the rest is done.
=> refactor(config): expose filesystem config

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/3-support-request.md
Switch headers to questions.
This allows removal of many of the descriptive comments.
closes #1394
=> fix: simplify issue templates

Dockerfile, cmd/connect.go, config/migrate/migrate.go
this is important for zero-input environments like docker and qri desktop, which need a surefire way to get to a running qri node without interruption. callers that want no prompts at all should now use:
```
$ qri connect --setup --migrate
```
To auto-run setup when the qri repo path is empty, and auto run migrations before startup.
=> feat(cmd): add migrate flag to connect command

base/transform_apply.go, dsref/load.go, fsi/status.go, lib/fsi.go, lib/load.go
sneaking in a little extra refactoring before we ship a release
=> refactor(fsi,base): remove calls to CanonicalizeDatasetRef from base.TransformApply, fsi package

remote/peer_sync_client.go
In `AddDataset`, if the ref is not complete (aka the `Path` & or
`ProfileID` are not set), we need to `ResolveHeadRef`. However,
`ResolveHeadRef` will override the `Path` field to fill in the HEAD
`Path`. If the `Path` was already specified, ensure that we add back the
intended `Path`
closes #1407
=> fix(AddDataset): preserve original path after `ResolveHeadRef`

logbook/logsync/p2p_test.go, p2p/bootstrap.go, p2p/connected.go, p2p/discovery.go, p2p/node.go, p2p/peers.go, p2p/profile_test.go, p2p/qri_peers.go, p2p/test/ipfs.go, p2p/test/p2ptest.go, p2p/test/testable_node_test.go
More recent libp2p updates have deprecated some packages that we were relying on. This commit points to the newer/correct packages
=> chore(libp2p2): adjust imports to point to non-deprecated packages

api/fsi_test.go, lib/datasets.go, lib/datasets_test.go
=> fix(lib.Get): add FSIPath when ref.Path is prefixed with "/fsi"

api/api.go, cmd/cmd.go, cmd/fetch_test.go, cmd/qri.go, cmd/ref_select.go, cmd/registry.go, cmd/save.go, cmd/whatchanged.go, lib/integration_test.go, lib/lib.go, lib/rpc.go, lib/rpc_test.go
CLI commands running over RPC were hanging after completion thanks to the RPC client side
instance never firing on the shutdown channel.
The fix for this was one line: add `go inst.waitForAllDone()` to lib.NewInstance when returning
an RPC-backed instance. All other changes are in service of testing that line.
* Moved the `ServeRPC` method down from the API onto the instance itself, making testing easier
* colocated all the rpc stuff into one file: rpc.go, which should make it easier to refactor
in the future
* re-worked some of the NetworkIntegrationTestRunner in lib, then realized it was overkill
for the RPC test.
=> fix(rpc): shut down gracefully after completed RPC call

registry/regclient/client.go
Previously we were just returning the string "registry", now we return
the address instead
closes #1419
=> fix(regClient): ResolveRef now returns registry address

base/log_test.go, cmd/log.go, cmd/save.go, cmd/save_test.go, dsref/spec/resolve.go, lib/datasets.go, lib/integration_test.go, lib/log.go, lib/remote.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/http.go, logbook/logsync/logsync.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p.go, logbook/types.go, remote/mock_client.go, remote/peer_sync_client_test.go, remote/remote_test.go
Prior to this commit we were _not_ recording push & delete operations in logbook. As per [RFC0030](https://github.com/qri-io/rfcs/blob/master/text/0030-replace_publish_clone_with_push_pull.md) we're now recording pushes of specific versions to a given remote within the oplog.
To do this, we make an optimistic write _before_ pushing or deleteing logs that adds an operation assuming it's successful. This way the receiver of the log gets the most up-to-date log that is signed with the operation included. If the push or delete operation fails, we roll back the log, removing the operation.
This approach tolerates faults better. the result of having an extra push / delete operation is less problematic than having a log that is short by one operation on a remote.
With this in place, logbook can …
=> feat(logbook): write push & pull operations, add logbook diagnostic output format

sql/preprocess/preprocess.go, sql/preprocess/preprocess_test.go
we have legacy users that include dashes, need to support sql'ing 'em.
closes #1388
=> fix(sql): properly handle dashes in dataset names

go.mod, go.sum, lib/lib.go
Using this option will disable bootstrapping to any qri or ipfs nodes
This has been confirmed to work via testground
depends on qri-io/qfs#42
closes #1434
=> feat(lib): `OptNoBootstrap` option func for `NewInstance`

api/api_test.go, event/p2p.go, go.mod, go.sum, lib/config_test.go, lib/datasets_test.go, lib/export_test.go, lib/fsi_test.go, lib/lib.go, lib/log_test.go, lib/profile_test.go, lib/remote_test.go, lib/render_test.go, lib/search_test.go, lib/test_runner_test.go, p2p/node.go, p2p/node_test.go, p2p/p2p_test.go, p2p/qri_peers_test.go, registry/regclient/client_test.go, registry/regserver/mock.go, remote/peer_sync_client_test.go, remote/remote_test.go
Also updates all tests to new `NewQriNode` api that requires an event bus. Most tests now use `event.NilBus`
This commit does not add any event `Publish`es, except for the `ETPGoneOnline` event. A previous version contained more event emissions & other changes that are relevant/similar to the `refactor_testground` branch. However, there didn't seem like a good stopping point, and this pr got bloated. Instead, I limited the changes, and will leave the events that relate to testgrounds/debugging to the `refactor_testground` pr.
=> feat(event): add p2p events to `events` and event bus to `QriNode`

Dockerfile
this'll fix breaking builds over at the docker auto-build: https://hub.docker.com/repository/docker/qriio/qri-auto
=> fix(docker): qri must be built from go 1.14 or higher

base/dataset_prepare.go, base/dsfs/dataset.go, base/friendly/friendly.go, base/revisions.go, base/save.go, lib/lib.go
this makes qri save --log-all actually do something useful. I think this is also a better general pattern for logging. Lots of debug statements. Maybe we should change --log-all to --verbose?
I'm again going to do a self-review b/c it's the weekend & we're trying to ship things
=> chore(logging): add debug logging along save path

lib/datasets.go, lib/lib.go, lib/resolve.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/http.go, logbook/logsync/logsync.go, logbook/oplog/log.go, logbook/oplog/log_test.go, remote/client.go, remote/remote.go
logbook was relying on an under-specified property of the `opstore.Logstore` interface: some  implementations _always_ fetch the Parent log as part of a Get request.
`logbook.UserDatasetBranchLog` was using this, which blew up when used with a different implementation. The solution to this is to push the logic needed by `logbook.UserDatasetBranchLog` into the oplog package, and implement it using explicit calls to a `oplog.Logstore`.
In the future I'd like to both work on the `Logstore` API and write a set of spec tests that implementations can validate against, much like we've done with `dsref.RefResolver`.
At the same time I've defined an exention interface that holds these explicit calls and an optional method logstores can implement to speed up this process. There are situations where …
=> feat(oplog): extension interface for sparse-parent logs

dsref/resolve.go, lib/resolve.go, lib/resolve_test.go
going back to shipping code with real tests again 😄. Cloud code uncovered this issue. It's panicking because the registry doesn't have a registry.
=> fix(lib): don't panic when resolving without a registry

cmd/setup.go, cmd/setup_test.go, lib/setup.go
Due to a recent refactoring, the `qri setup` command was no longer prompting for a username. This caused the username validation to fail. Passing a username via the `--username` flag was also ignored, as the code in lib/setup.go would overwrite it. Fix these problems, add tests to make sure they won't happen again.
Rename the `--peername` flag to `--username` for `qri setup`
=> fix(setup): Fix setup, add many unit tests

p2p/bootstrap.go, p2p/node.go, p2p/peers.go
We already `log.Debug` that there was an upgrade error inside `upgradeToQriConnection`, there is no need to also `log.Error` this message as well. We expect that many of the connections that we will be making will not "speak" qri. This shouldn't be an error.
Also, when we connect directly to a peer using `qri peers connect`, since the command expects the peer's profile as a return value, we need to explicitly upgrade the connection so we know that the profile exists in the Profile store.
When we refactor, we really should be listening on a channel that is monitoring the profile exchange process & only trying to access the peer profile then. This is a temporary solution.
=> fix(p2p): some clean up around `qri peers connect` and `upgradeToQriConnection`

sql/preprocess/preprocess.go, sql/preprocess/preprocess_test.go
this makes simple statements much easier to write, as users don't have to juggle dataset aliasing.
* the first un-aliased dataset will be automatically aliased to `ds`
* subsequent datasets will be `ds2`, `ds3` ... and so on
* BUT! select statements that reference columns without aliases will error
this error is because preprocessing happens before we have any schema information, making it a non-trivial operation to automatically disambiguate column references in select statements.
=> feat(sql): auto-alias table names when only one dataset is referenced

api/api.go, api/webui.go, config/api.go
This allows qri to serve a webui at `localhost:2503/webui`
The webui makes requests to the qri api at `localhost:2503`, since this was the specified "BACKEND_URL" when bundled.
However, we maybe can dynamically set this for the webui, by using the baseurl of the URL that is serving the webui.
We also have `http://localhost:2503` as an allowed content provider in our html's 'Content-Security-Provider', this is easy enough to fix, with golang templates and a field called `WebappUrl` or `RemoteUrl` or something in the config.
-----
Edit: turns out this wasn't an issue at all, was able to adjust the webapp and everything worked great! You can test yourself that it doesn't rely on `localhost:2503` by changing the port on which you are serving the API, and checking the webui at that port
=> feat(api): qri can serve a simple webui

cmd/print.go, cmd/validate.go, cmd/validate_test.go, go.mod, go.sum, lib/datasets.go, lib/datasets_test.go
🕺 fancy demo:  https://asciinema.org/a/ThZ0dfFnnVasD0SAusozNR6Vo
make default output easier to interpret by formatting results as a table. when body data is tabular (structure.depth of 2), split path into "ROW" / "COLUMN" columns for easier reading.
Add an "output" flag that supports modifying the resulting output.
closes #1530, closes #1531
=> feat(validate): tabular output of validation errors on CLI, configure output format

.circleci/user_benchmarks.sh, cmd/fsi_integration_test.go, cmd/init.go, cmd/remove_integration_test.go, fsi/init.go
Also, added examples to the `qri init --help` message
PR adding `body` flag to quickstart cli tutorial forthcoming.
closes #1524
=> refactor(init): rename flag `source-body-path` to `body`

DEVELOPERS.md, cmd/cmd_test.go, cmd/connect.go, cmd/qri.go, go.sum
=> bug(profile): add check for qri config before running code against it

base/dataset_prepare.go, base/dataset_prepare_test.go, base/validate.go, cmd/validate_test.go, fsi/fsi.go, go.sum, lib/datasets.go, lib/datasets_test.go, lib/load.go
- Pull out logic from `InferValues` and create `InferStructure` function that infers a structure from a body. Adjust tests to test `InferStructure` directly.
- Adjust `lib.Validate` to use `ParseAndResolveRefWithWorkingDir` & `fsi.FilesystemPathToLocal` (to catch any fsiPath), rather then `CanonicalizeDatasetRef`
- Add `TestDatasetRequestValidateFSI` to catch errors when trying to validate a fsi dataset w/ no history
closes #1535
=> fix(`Validate`): allow validation of FSI dataset w/ no history

event/dataset.go, event/filesystem.go, event/remote.go
to keep over-the-wire coding consistent, use lowerCaseFieldNames for any struct that's being sent as an event & piped over a websocket.
=> fix(event bus): encoded fields use lower-case names in JSON

cmd/connect.go, lib/lib.go, lib/setup.go
If a user runs `qri connect --setup`, but already has a repo, proceed
forward with spinning up the qri daemon. Only run `DoSetup` if a
repository cannot be found.
=> fix(connect): only run `DoSetup` if there is existing repo

lib/fsi.go, lib/fsi_test.go, lib/lib.go, lib/lib_test.go, lib/test_runner_test.go
Some FSI tests check explicit paths. For now, always use POSIX style forward slashes, instead of mixing them with Windows slashes. Increase the timeout for event bus publishing.
Treat "event bus is closed" event as debug, instead of error
=> test(windows): Fix lib/ unit tests for Windows platform

sql/qds/datasource.go
This fixes the symptom in #1503 though I know it's likely this isn't the best way to deal with it. At least it points to where the problem is.
Basically, `xristosk/bandcamp_artists` (in its current version, as I type) has more columns than column headers in its csv representation. This causes an index error when doing a join against another table. This fix just truncates the row to match the headers. These unnamed columns don't show up on [the qri.cloud page](https://qri.cloud/xristosk/bandcamp_artists) either, so I figured maybe you've been truncating it elsewhere in the codebase as well.
=> fix(sql): Truncate unexpected columns during join

api/fsi.go, api/fsi_test.go, cmd/fsi_integration_test.go, cmd/init.go, cmd/test_runner_test.go, fsi/init.go, fsi/init_test.go, fsi/status_test.go, lib/datasets_test.go, lib/fsi.go, lib/fsi_test.go, lib/test_runner_test.go
Prior to this change, lib.InitDataset would take two parameters, Dir which would need to exist already, and Mkdir which would be created but could only be a single directory name instead of a relative path. Fix this problem, and also add multiple tests, and cleanup some TODOs.
=> fix(init): TargetDir for init, can be absolute, is created if needed

api/datasets_test.go, api/testdata/expect/TestDatasetGet.test_ds.json, sql/sql_arm.go
My comments on the previous PR (dsfs overhaul) were misinformed. I thought dstest was doing work to drop components from datasets, or just not comparing them. Turns out it was actually a bug in how the api tests were calling json.Unmarshal
The API response looks like this:
```
{
"data": {
"peername": ...
"name": ...
"dataset": {
"peername": ...
"name": ...
```
By unmarshalling response.Data, the top-level fields for peername, name, etc were honored, but the result would have no components. Instead, we should unmarshal response.Data.Dataset, in order to get everything.
Previously the golden file had only 4 top-level fields. With this fix, now it has everything.
=> fix(api): Fix unmarshal bug in api test

Makefile, README.md, api/api.go, cmd/version.go, go.mod, go.sum, p2p/p2p.go, remote/client.go, startf/transform.go, version/version.go
before:
```
$ qri version
0.9.14-dev
```
after:
```
$ qri version
version:	0.9.14-dev
build date:	2020-11-30T20:32:33Z
git summary:	v0.9.13-56-gb6834436-dirty
git branch:	feat_version_add_git_info
git commit:	b6834436
git state:	dirty
golang version:	go1.15
```
Also adds  `$ qri version --format=json` flag to get this info printed as JSON, which tools like qri desktop's `main` process may be able to make use of
=> feat(version): add info from git and golang to qri version command

Dockerfile, Makefile
fix an issue in makefiles that's super prominent when make is used in conjunction with dockerfiles, drop size of production docker images from ~586MB to ~75MB
=> chore(dockerfile): use two-image build

base/dsfs/compute_fields.go, base/dsfs/dataset.go, base/dsfs/dataset_test.go, cmd/testdata/movies/dataset.json, repo/test/testdata/cities/input.dataset.json, repo/test/testdata/counter/input.dataset.json, repo/test/testdata/craigslist/input.dataset.json, repo/test/testdata/flourinated_compounds_in_fast_food_packaging/input.dataset.json, repo/test/testdata/movies/input.dataset.json, repo/test/testdata/sitemap/input.dataset.json
This will let [qri-git](https://github.com/qri-io/qri-git) match timestamps from git on import.
setting the input dataset commit.Timestamp value will now be preserved instead of being overwritten with the current time. Input timestamp will ALWAYS be converted to UTC time zone.
This change makes it much easier to generate dataset histories with commit timestamps that aren't in chronological order, which is perfectly fine according to spec, but will cause bugs for any code that relies on such an assumption.
=> feat(save): support custom timestamps on commit

base/archive/archive_test.go, base/dsfs/commit.go, base/dsfs/compute_fields.go, base/dsfs/dataset.go, base/dsfs/dataset_test.go, base/dsfs/testdata_test.go, base/dsfs/transform_test.go, base/save.go, base/save_test.go, cmd/print.go, cmd/print_test.go, cmd/qri.go, cmd/save.go, event/dataset.go, event/event.go, event/remote.go, go.mod, go.sum, lib/lib.go, lib/load_test.go, lib/websocket.go, remote/client.go, remote/mock_client.go, remote/remote_test.go, repo/test/test_repo.go
add save event publication to `dsfs`, move all progress bar output up into `cmd` package and replace progress bar package with `mpb` which has explicit support for displaying multiple progress bars at once. To pull this off `lib.Instance` gets
a new `inst.Bus()` accessor method.
This setup brings progress bar output closer to the way desktop / API driven events display progress.
This PR mainly lays the foundations of getting a save progress bar up. On truly large datasets the progress reported will kinda hang for a while around 10% completion while the body file is processing, then suddenly jump to 90%, and finish. This is  because we don't have an API in `qfs` for getting the size of a file, so we can't properly track expected time to ingest. I'll ship the fix for that once we land some …
=> feat: save progress bars

base/dsfs/commit.go, base/dsfs/compute_fields.go, base/dsfs/structure.go, go.mod, go.sum, logbook/logbook.go, logbook/logbook_test.go
@chriswhong was getting a spinning-wheel on save that was hanging forever on a very small dataset. Turns out it's a concurrency problem.
The dsfs.computeFieldsFile `Read` and `handleRows` methods were both contending for the same mutex lock, which would deadlock the program. Fix this by using a `dsio.TrackedReader` to count bytes instead of local state, which drops the need for taking the lock on calls to `Read`. Should yeild a microscopic performance bump as well.
Another problem that crops out of this state: users understandably use SIGKILL to get out of the hung process, which is leaving the dataset name "taken" and causing errors on re-running save.
If a user starts the save process but abandons it midway with SIGKILL qri's currently structured to terminate without any cleanup. This …
=> fix(save): remove dataset field computing deadlock

changes/changes.go, changes/changes_test.go
Change reports now allocate column diffs based on max unique columns detected not by length of the left or right side.
=> fix(changes): column renames are properly handled now

config/config.go, config/migrate/migrate.go, config/migrate/migrate_test.go, config/migrate/testdata/two_to_three/qri_config.yaml, config/p2p.go, config/testdata/simple.yaml
This is to be merged AFTER the cloud migration. All new clients will default to the new bootstrap addresses. Old ones will continue using the current ones until we have the next config migration where we aim to switch to DNS backed addresses.
=> chore(p2p): update bootstrap addresses

config/config.go, logbook/logbook.go, logbook/logbook_test.go, logbook/logsync/logsync.go, logbook/logsync/logsync_test.go, logbook/logsync/p2p_test.go
It should always be the case that the data within a logbook matches the reference that logsync says it is pushing. No need to keep this behavior inside of a hook.
This change causes `TestP2PLogsync` to hang. I don't know what is causing this, but could dive into it in the near future.
=> fix(logbook): Logsync validates that ref has correct profileID

api/api.go, api/middleware.go
Adds `Mux` field to `Server` struct (type `http.ServeMux`). A new `Mux`
is created in the `api.New` function when it returns a new `Server`.
The `Middleware` and `NoLogMiddleware` functions are now exported.
closes #1611
=> refactor(api): adjust `Server` & middleware funcs to make the qri api more extensible by outside packages

key/store.go, lib/lib.go, profile/store.go, repo/buildrepo/build.go
Real runs of qri read the config from a path, which sets that path. Most tests use a mem repo. The test TestNewInstanceWithAccessControlPolicy uniquely uses a fs repo but that config doesn't know the repo path. By not setting that path, running this test would create json and json.lock files when creating a KeyStore and ProfileStore.
Fixes https://github.com/qri-io/qri/issues/1601
=> fix(repo): Don't use blank path for new repo in tests

api/transform.go, cmd/apply.go, lib/test_runner_test.go, lib/transform.go, lib/transform_test.go
First of several to come for transitioning from RPC to HTTP and moving `context` up to `api` & `cmd`
=> refactor(apply): RPC > HTTP

lib/transform.go
I made a mistake while rebasing the recent apply RPC > HTTP PR which ended up not keeping the proper endpoint. This fixes it.
=> fix(apply): bad API endpoint for apply over HTTP

api/api.go, api/datasets.go, api/remote.go, cmd/list.go, go.mod, go.sum, lib/datasets.go, lib/datasets_test.go, lib/http.go, lib/params.go
Based on the work in https://github.com/qri-io/qri/pull/1633 this is to land the baseline refactoring and and example with List.
Subsequent PRs will convert rest of the handlers/endpoints to this format and move to the HTTPClient. 
Lastly the "not clear cut" endpoints like `/get/` and `/save` will be refactored and/or split.
=> refactor(api): introduce UnmarshalFromRequest, update List API

lib/registry.go, lib/registry_test.go, logbook/logbook.go, logbook/oplog/log.go, registry/regserver/handlers/handlers.go, registry/regserver/handlers/profile.go
When a user runs `prove`, the response they get back contains the original profileID and logbook data. Assign that data to their profile.
=> fix(prove): Prove command updates local logbook as needed

base/remove_test.go, dsref/parse.go, dsref/parse_test.go, dsref/ref.go, dsref/ref_test.go, dsref/spec/resolve.go, lib/integration_test.go, logbook/logsync/http.go, logbook/logsync/logsync.go
This is a backwards-compatible spec change to the way we parse dataset reference strings, specifically the concrete part of a ref (the bit after the `@`). The grammar change from this:
```
<concreteRef> = '@' [ <profileID> ] '/' <network> '/' <commitHash>
```
to this:
```
<concreteRef> = '@' [ <datasetID> | <profileID> ] '/' <network> '/' <commitHash>
```
The only change is replacing `profileID` with `datasetID`, where `datasetID` is a lowercase-base32 dataset identifier (initID). This change makes it possible to reference datasets by ID directly. For example:
@jzk63pfkfefgwub7wvhl54s4inqr25ncwhmi7svahjjxzwuknrlq
@jzk63pfkfefgwub7wvhl54s4inqr25ncwhmi7svahjjxzwuknrlq/ipfs/QmHaash
We can make this change backwards-compatible because dataset identifiers & profileIDs use different character …
=> refactor(dsref): replace ProfileID with InitID in refstring serialization

api/datasets.go, api/http_client_test.go, cmd/list.go, lib/datasets.go, lib/datasets_test.go, lib/http.go, lib/integration_test.go, lib/params.go
Merged listRawRefs into the list API and converted from RPC to HTTP along with some bug fixes.
=> refactor(list): RPC > HTTP for raw refs

cmd/completion.go, cmd/config.go, lib/config.go, lib/config_test.go, lib/datasets_test.go, lib/http.go, lib/lib_test.go, lib/rpc.go
=> refactor(config): RPC > HTTP & API for config

api/api.go, api/api_test.go, api/datasets.go, api/datasets_test.go, api/fsi.go, api/fsi_test.go, api/log.go, lib/api.go, lib/fsi.go, lib/http.go
building on ideas from #1650, this adds the first method where the HTTP handler is generated by package lib, but mapped to an endpoint by package api.
This PR is mainly to establish the patten & talk through repercussions. Right now this only works for formats where the response format is well known / singular.
=> lib.NewRequestHandler removes boilerplate from api package

api/api.go, api/datasets.go, api/datasets_test.go, changes/changes.go, lib/changes.go, lib/changes_test.go, lib/datasets.go, lib/diff.go, lib/dispatch.go, lib/fsi.go, lib/scope.go
Lays groundwork for other upcoming `DatasetMethods` method conversions by creating `datasetImpl` struct, `Name` method (needed to satisfy the `MethodSet` interface), and all corresponding `datasetImpl` methods
Fixes a bug in `changes` that occurred when only `rightRef` was present.
=> refactor(changes): use `Dispatch` with `lib.ChangeReport` function

api/api.go, api/datasets.go, api/remote.go, cmd/preview.go, cmd/push.go, cmd/remove.go, lib/http.go, lib/integration_test.go, lib/lib_test.go, lib/remote.go, lib/rpc.go
Still have to manually test this before actually marking as done.
Another interesting bit is the modification to `lib/http.go` where it now encodes some query params if you pass in a `map[string]string` which was needed for the `DELETE` request on the `AEPush` endpoint
=> refactor(remote): RPC > HTTP & API for remote

api/datasets.go, cmd/ref_select.go, lib/access.go, lib/api.go, lib/changes.go, lib/config.go, lib/datasets.go, lib/diff.go, lib/dispatch.go, lib/dispatch_test.go, lib/fsi.go, lib/http.go, lib/lib.go, lib/render_test.go, lib/transform.go
Originally prototyped by https://github.com/qri-io/qri/pull/1687, this change adds an "Attributes" method to each MethodSet. For now, this is only defining the HTTP endpoint and verb, but in the future can include things like permissions, data structures that need locking (logbook and profile store etc), and more.
We can then delete some of the earlier hacks put in place for Dispatch, such as methodEndpoint function.
For now, endpoints only allow a single HTTP verb. We may find we need to allow a list of verbs instead, but if so, need a way to determine which verb to use when calling a method over HTTP RPC.
Open question on which of these directions to go:
1) should the endpoint urls should remain in lib/api.go, with Attributes using the constants
2) should we keep the endpoint urls in …
=> feat(dispatch): Methods attributes to hold metadata about methodSets

lib/changes.go, lib/datasets.go, lib/diff.go, lib/lib.go
New DatasetMethods don't use anything on the Instance aside from Dispatch. Switch them all to use the dispatcher interface, in order to guarantee that this fact holds.
=> fix(dispatch): Use dispatcher interface for DatasetMethods

cmd/checkout.go, cmd/save.go, cmd/save_test.go, fsi/init.go, lib/datasets.go, lib/diff.go, lib/dispatch.go, lib/fsi.go, lib/fsi_test.go, lib/params.go, lib/params_test.go
Background: when `qri connect` is running, it holds an exclusive lock, and other invocations of qri will send their commands to that connected process using RPC. The two processes may be running in different directories, so it is necessary to change file paths to be absolute before sending the params across RPC. Before, we would do this explicitly, which was error-prone and
easy to forget about, since the broken behavior would not happen in the common case.
The proposed solution implemented here adds tags to structs that are passed to methods. Most use `qri:"fspath"` to specify fields that are file system paths. Diff is special and uses `qri:"dsrefOrFspath"` because its inputs can be either dsrefs or file paths. Adding this behavior for new commands is simple; it just requires adding this …
=> feat(dispatch): Abs paths on inputs to dispatch methods

api/sql.go, api/testdata/api.snapshot, cmd/factory.go, cmd/factory_test.go, cmd/get.go, cmd/get_test.go, cmd/pull.go, cmd/qri.go, cmd/sql.go, lib/datasets.go, lib/dispatch.go, lib/integration_test.go, lib/lib.go, lib/scope.go, lib/sql.go
Use the Dispatch pattern for sql methods.
Instead of source being a parameter that is passed down the callstack, until code calls LoadDataset or ParseAndResolveRef, attach source to the scope. This will let us remove the source from the interface, since the callsite of LoadDataset doesn't care about source, the concrete implementation of the Loader does. Clients of lib can configure the source just-in-time by using WithSource on the Instance.
Also, discovered that the --offline flag for sql was broken, so resolution would never be local-only. The cause was ParseResolveFunc always using the defaultResolver. This type of cleanup should make these sorts of bugs much harder to cause.
Finally, remove the ResolverForMode function from scope. Only lib.Save was using it, but in actually it only …
=> refactor(sql): Dispatch for sql. Move resolver source to scope

api/api.go, api/datasets.go, api/datasets_test.go, lib/api.go
`AESave`, `AEPull`, & `AERemove` endpoints are all handled using `NewHTTPRequestHandler`
`AEPeerList` & `PeerListHandler` is removed
Removes associated tests.
closes #1721
=> refactor(api): remove unneeded `DatasetHandlers`

api/http_client_test.go, cmd/pull.go, cmd/remove.go, cmd/validate.go, lib/access.go, lib/automation.go, lib/collection.go, lib/config.go, lib/datasets.go, lib/diff.go, lib/dispatch.go, lib/dispatch_test.go, lib/fsi.go, lib/http.go, lib/log.go, lib/peers.go, lib/profile.go, lib/registry.go, lib/remote.go, lib/search.go, lib/sql.go
Attributes has a field for the default source for the method. This lets us remove the WithSource calls throughout the cmd package, and makes tests more readable.
=> fix(dispatch): Add default source resolver to Attributes

docs/api_doc_template.yaml, docs/api_docs.go, docs/go.mod, docs/go.sum, lib/api.go, lib/datasets.go
Closes: https://github.com/qri-io/qri/issues/575
~~Still missing: `get` routes~~
=> docs(api): add non lib routes to spec

api/api.go, api/endpoints.go, api/handlers.go, api/http_client_test.go, lib/api.go
The `lib` package was defining endpoints that don't have any relation to
methods defined in lib. These endpoints have been moved into `api/endpoints.go`:
```
AEHome
AEHealth
AEIPFs
AEWebUI
AEUnpack
```
closes #1776
=> refactor(lib, api): move sugar endpoints out of `lib` into `api`

lib/routes.go
Closes: https://github.com/qri-io/qri/issues/1775
@dustmop noticed that writing the issue was more work than this commit. Sorry.
=> fix(routes): skip over endpoints that are DenyHTTP

docs/docs.go
hmmm, these changes probably should have gone through before the release, but I updated the "table of contents" part of the docs generator. have an issue open about it (https://github.com/qri-io/qri/issues/1784), but in the future we should probably generate those as well.
=> fix(docs): update table of contents

registry/regserver/handlers/handlers.go, remote/registry/regserver/handlers/handlers.go, remote/remote.go, remote/remote_test.go
Updating remaining routes to `gorilla.mux` and bringing it in line with the rest.
=> fix(remote): update handlers with gorilla mux

api/api.go, api/api_test.go, cmd/fetch_test.go, lib/lib.go
I'm in a place with really spotty internet, and need to work on qri frontend without blowing up the router. This change makes it possible to run qri connect with p2p features disabled. I've renamed lib.Instance.Connect -> lib.Instance.ConnectP2P to clarify that it's really just about p2p connections, and defined a canonical error for trying to connect with disabled p2p via configuration.
Output when running connect without p2p doesn't make allusions to the d.web, and skips listing libp2p addresses (because there are none).
=> fix(api): don't error when running connect with disabled p2p

Makefile, api/api.go, config/config.go
Small tweaks to improve connection UX from the command line.
Remove websockt & RPC values, which are no longer in use. Stagger printout while initial ports are being acquired. Print version number first.
=> refactor(connect): re-work connection detail printout for qri connect

collection/collection.go, collection/collection_test.go, collection/migrate.go, collection/migrate_test.go, collection/spec/collection.go
fleshing out a local collection implementation using lessons learned from #1804. This PR adds an unused-but-tested migration function, and clarifies that specs for event subscriptions must be optional.
=> local collection migrates from repo, updates via event bus subscriptions

cmd/search_test.go, lib/api.go, lib/lib.go, lib/search.go, registry/regclient/client.go, registry/regclient/search.go
Aligning the search response format and registry response parsing.
=> fix(search): use consistent naming and output format for search

docs/api_doc_template.yaml, docs/api_docs.go, docs/docs.go, lib/access.go, lib/automation.go, lib/datasets.go, lib/fsi.go, lib/params.go, lib/peers.go, lib/profile.go, lib/remote.go, lib/sql.go
see docs by navigating to project root & running `make serve-api-docs`, then load `http://localhost:2502` in a browser.
after this PR, comments in the lib package have two new rules:
* comments can have at most one semicolon, which separates comments into `[description];[example]` sections
* a single example value is now supported when prefixed with 'e.g.', example values should match their syntax type (string examples should be "quoted", boolean examples should be true, numeric should be 2.145)
note that _only_ `e.g.` will work to create an example, not `eg.`, which I continually mistype
I also put these new changes to immediate use, annotating a slew of input structs with JSON tags to clean up their documentation & narrow field name case sensitivity
=> Support docs examples from source comments, add json struct tags to lib input parameters

base/dataset_prepare.go, cmd/save_test.go, dscache/dscache.go, dsref/mem_resolver.go, dsref/spec/resolve.go, logbook/logbook.go, remote/client.go, remote/server.go, repo/fs/fs.go
adding in human elements like username & name, along with HEAD path. We need this now because the automation subsystem is the first one to properly store _just_ initIDs
=> feat(resolver): resolving a reference w an initID completes the ref

automation/orchestrator.go, automation/orchestrator_test.go, automation/spec/workflow_store.go, automation/workflow/filestore.go, automation/workflow/filestore_test.go, automation/workflow/store.go, lib/automation.go
Adds a context to all store operations. This is required for the cloud side of implementation and probably any alternative store would also benefit from it. Useful also for later on if we want to branch this stuff out from a single node.
=> refactor(workflow): supply context to all workflow store ops

auth/token/token.go, auth/token/token_provider.go, base/dataset.go, base/ref.go, base/save.go, collection/collection.go, collection/collection_test.go, collection/spec/collection.go, dscache/convert.go, dscache/convert_test.go, dscache/dscache.go, dscache/dscache_test.go, lib/access.go, lib/automation.go, lib/collection.go, lib/dispatch.go, lib/lib_test.go, lib/registry.go, profile/id.go, profile/id_test.go, profile/profile.go, profile/store.go, remote/access/access.go, remote/server.go, remote/signature_test.go, repo/ref/convert.go, repo/ref/dataset_ref.go, repo/refstore.go, repo/serialize.go, repo/test/test_repo.go
Add methods to profile.ID called Encode and Validate. Encode replaces the old String function, and base58 encodes an ID. The old String function now outputs wrapped hex, to make it clear that profile.IDs have different shape from base58 encoded strings. The Validate method ensures that a profile.ID is not double-encoded. Use this function in collection.Set to prevent callers from breaking their collection by passing invalid IDs.
Fixes #1857
This refactoring was performed by renaming the old `profile.ID.String` method (to `Stringz`) then fixing all of the compilation errors this caused. This renaming uncovered that the function `CompareDatasetRef` was relying on the implicit base58 encoding that `fmt.Errorf` performs.
=> refactor(profile): profile.ID.Encode and Validate methods

event/automation.go, lib/automation.go, lib/automation_test.go, lib/lib.go, lib/scope.go
Always add the profileID to the scope's context. This is used by automation and will soon be used by the event.Bus as well. Allow scope to detach their parent context, so that they can be used for long-running operations that should not be cancelled by their parents.
=> feat(scope): Scope has profileID. ReplaceParentContext method

automation/orchestrator.go, automation/spec/workflow_store.go, automation/workflow/filestore.go, automation/workflow/store.go, collection/collection_test.go
The current local store implementations don't really need to filter by ownerID, but other implementations might. This is just passing it in to enable the store to surface the option. Business logic whether that's used lives in `lib`.
=> refactor(wf_store): pass in ownerID to enable filtering

collection/collection.go, collection/spec/collection.go, docs/go.sum, event/dataset.go, go.mod, go.sum, lib/automation.go, lib/datasets.go, p2p/node.go
1) update to latest qfs to fix nil ctx bug
2) ensure we have a default source for `deploy`, this extends to the deferred `Remove` that gets triggered if something goes wrong with the deploy
3) adjust the deploy path to only attempt to remove the just saved version if we have an error while deploying after the dataset has saved. If the error occurs during the save, the `Save` path has its own clean up. Also, ensure we are only removing the previous version if this current deploy has saved a previous version. If there were no changes to save, don't erroneously remove a version.
4) Collection needs to be updated when a dataset creation fails. The collection catches the dataset creation information very early in the save process, so we need to also be updated if the creation fails, so that we …
=> fix: deploy panics, double version removal, collection clean up

lib/automation.go, lib/automation_test.go
So the frontend can correctly track runs, and so the frontend's http
requests do not time out if a run lasts very long, return the runID, and
only error if there is something wrong with the request params
=> fix(lib): `lib.Run` should mirror `lib.Deploy` return ASAP behavior

automation/orchestrator.go, collection/collection.go, collection/spec/collection.go, event/automation.go
We were previously using the `ETAutomationDeploy` events, but unfortunately they don't actually have enough specificity for us to know exactly what is going on when we catch the events in the collection.
We need to follow the same patterns we are using to add to the collection when a dataset is added or removed: rely on events emitted at those exact times.
We need an `ETAutomationWorkflowCreated` and an `ETAutomationWorkflowRemoved` event to let us know that a workflow has been added or removed.
=> refactor(collection): rely on `ETAutomationWorkflowCreated` events

logbook/oplog/log.go
a prior logbook implementation erroneously used logbook identifiers in the AuthorID field when they should have been using external author Identifiers.
In the short term we're relying on the fact that the 0th operation always uses an external identifier
=> fix(logbook): resolve by AuthorID should always use external identifiers

collection/collection.go
fixes bug that meant any time we added a new version of the dataset, we would also override the workflow id, run status, and previous run id.
=> fix(collection): maintain `WorkflowID` and run information in collection

collection/spec/collection.go, lib/automation.go
add test to prove that if one user `pulls` a dataset, it doesn't effect another user's collection
=> test(collection): tests for workflow & new version creation

automation/orchestrator.go, base/dataset_test.go, collection/collection.go, collection/collection_assert_test.go, collection/collection_test.go, collection/migrate.go, collection/migrate_test.go, lib/collection.go, lib/lib.go, lib/lib_test.go, lib/scope.go, remote/mock/client.go
Because we need to repeat many of these handler/event patterns in `cloud`, we are dividing up the `Collection` to make it more reusable. 
The `Collection` is now a struct that contains a `WritableSet`. The `Collection` is responsible for listening to events and calling various `Put`-like functions on the `WriteableSet` when certain events are handled. 
To keep things moving, rather than refactor a ton about the `collection` package, first I'm keeping these `Put`-like functions as close as possible to the methods that already existed on `localSet`. These can most likely be narrowed in future prs.
The `spec` package as been remove, and the tests moved into the `collection` packages itself. Although, `AssertWritableCollectionSpec` with some tweaking and additional tests should probably be …
=> feat(collection): expand `WritableSet` interface, add option to pass in custom `WritableSet`

automation/orchestrator.go, automation/orchestrator_test.go, automation/run/filestore.go, automation/run/filestore_test.go, automation/run/run.go, automation/run/store.go, automation/spec/run.go
Also added an `owner profile.ID` to `ListByStatus` as cloud will have to scope it down and from a multi tenancy standpoint makes sense to control for it. And I want to avoid hacks we used to do where we magically pull out the relevant user from context.
=> fix(run): add ctx to run.Store

api/handlers.go, api/open_api_3.yaml, api/spec/testdata/aggregate.json, cmd/cmd_test.go, cmd/list.go, cmd/stringers.go, collection/collection.go, collection/collection_assert_test.go, dscache/dscache.go, dscache/dscachefb/RefEntryInfo.go, dsref/version_info.go, event/dataset.go, event/remote.go, lib/collection.go, lib/collection_test.go, lib/http/api.go, lib/params.go, logbook/logbook.go, repo/ref/convert.go
=> refactor(*): add "aggregate" fields to `VersionInfo` & listen for cloud event in `collection`

collection/migrate.go, collection/migrate_test.go, logbook/logbook.go
=> fix(collection): use `logbook` to fill in missing run and commit count data during `collection` migration

lib/datasets.go, transform/transform.go, transform/transform_test.go
We rely on the init id in the `TransformLifecyle` event in the
collection and on the frontend to coordinate the events to their proper
datasets. I had an incorrect assumption, and did not realize that the 
datasets passed down to `transform.Commit` would not have their 
`dataset.ID` fields populated.
Instead, we need to pass down the InitID for the dataset (if it exists)
directly into the call to `transform.Commit`. The save path seems to
expect the the ID field NOT be passed in when we go to save the dataset,
which is why I did not choose to just ensure the `dataset.ID` field was
populated before passing the dataset down into `transform.Commit`.
It is not a problem if the `InitID` field is not populated, and it is
actually expected that this field is not populated for "apply" runs.
=> fix(transform): need to pass down InitIDs to `transform.Commit`

transform/startf/ds/dataset.go, transform/startf/testdata/set_meta.star, transform/startf/transform.go, transform/startf/transform_test.go, transform/transform_test.go
closes #1907 
also closes qri-io/frontend#254
=> refactor(startf): transforms should return a dataset with the `Structure.Entries`

cmd/cmd_test.go, cmd/save_test.go, lib/automation_test.go, transform/startf/ds/dataset.go, transform/startf/transform_test.go, transform/transform_test.go
with our latest switch to using `ds.body` assignment, we've lost the `parse_as` argument that we formerly relied on to set data format. As a short-term fix we'd like to _default_ to CSV data format.
In a follow-up we'll detect the number of dimensions in the body and error if it's higher than 2.
closes #1915
=> fix(transform): transforms default to CSV format

lib/datasets.go
Fix for https://github.com/qri-io/frontend/issues/299
Currently only supports `limit` & `offset` params, but user facing endpoints should take in `page` & `pageSize` too.
=> fix(get): extend pagination on /get

automation/orchestrator_test.go, automation/run/filestore_test.go, automation/run/run.go, automation/run/run_test.go
@ramfox This made a lot of issues in parsing the runs from the run store and introduces some follow up behavior issues. 
The only gotcha is that we have to make sure all the payloads do actually conform to the `event.TransformMessage` payload type which I'm still not a 100% on as it's a bit hard to track down.
=> fix(run): run store deserialization updated

lib/websocket/websocket.go
Using the http request context as the context for `read` causes the connection to close early. The examples used in the `nhooyr/websocket` repo do not cause this issue, so not totally sure what the error is here. However, in order to have the context survive, we need to use the background context. Thankfully, if the connection closes we are able to catch it in the `read` function. It will error and we can prune the connection. This will have to do until we can devote more time to understand what is going wrong.
=> fix(websocket): request context causes early cancellation

lib/automation.go
Missed this on my first pass because I figured this scoping was taken care of using the `newScopeFromWorkflow` function. However, this only scopes the `scope.Context` not the `scope.AppContext`, which is what we need in `lib.apply`.
Since the `lib.run` and `lib.apply` use the `scope` for the `newScopeFromWorkflow` differently, I thought it best to adjust the scoping issue in `lib.apply` only, rather than `newScopeFromWorkflow`. If there comes a time when `scope.Context()` for both workflow runs and workflow applies are both expected to last the context of the app itself, we may want to make this adjustment in `newScopeFromWorkflow` instead.
=> fix(lib): scope the `lib.apply` context

automation/orchestrator.go, automation/orchestrator_test.go, automation/run/run.go, collection/collection.go, event/transform.go, lib/automation.go, lib/http/api.go, transform/transform.go
closes #1946 
Also fixes some `orchestrator.runLock` errors.
=> feat(automation): `CancelRun` will cancel run associated with the `runID`, if that is the run that is running

lib/lib.go
whelp, intro-ed a bug and now fixing it. Go routine to log that the instance context has canceled never returned properly.
=> fix(lib): go routine to assure instance context cancellation now closes properly

automation/orchestrator.go, automation/orchestrator_test.go, automation/run/run.go, automation/run_queue.go, automation/run_queue_test.go
First pass at a basic `RunQueue` interface.
Only 1 queue for both dry runs and runs, no priority.
Once we have a better understanding of how we want to deligate in cloud & how we want the runs scoped (can we run one dry run and one run at a time? Can a user run mulitple runs at a time, or is it scoped one per user) we can expand how we see fit.
--
Also fixes flaky `TestRunStoreEvents` test!
Interestingly enough, there were two problems with the test both stemming from the same issue: since so much of our run process happens async, events are not guaranteed to emit in the same order at the same time. 
In the test as it was, we were comparing the contents of the run store after each emitted transform event. This all happened in the correct order, because we were mocking the run so we could …
=> feat(automation): `RunQueue` interface to sync & cancel runs

automation/orchestrator.go, automation/orchestrator_test.go, cmd/apply.go, cmd/system.go, cmd/system_windows.go, docs/go.sum, go.mod, go.sum, lib/automation.go, lib/automation_test.go, lib/datasets.go, lib/lib.go, transform/startf/ds/bound.go, transform/startf/ds/dataset.go, transform/startf/ds/dataset_test.go, transform/startf/sandbox.go, transform/startf/transform.go, transform/transform.go, transform/transform_test.go
Depends on https://github.com/qri-io/starlib/pull/146
This PR adds terminal size detection to `qri apply`. The width and height of the terminal is passed down to `lib/` and eventually to `transform/` and `starlib/dataframe/`, where it affects how DataFrames get stringified. Users of the http api can also send this same info via normal arguments, in order to match the correct size of whatever html element they are going to display upon.
The first commit refactors the automation orchestrator a bit, to make passing this info a bit easier. Some new nomenclature is introduced here: rather than `Run` for runs that commit and `Apply` for runs that do not commit, this change uses `RunAndCommit` and `RunEphemeral`. The idea is that `apply` as a piece of terminology was intended as a high level …
=> feat(transform): Detect terminal size, pass it to transform to affect DataFrame rendering

automation/run_queue.go
run queue events need to be transmitted over the websocket so the frontend can respond correctly
=> fix(RunQueue): scope events to the ownerID of the run

collection/collection.go, collection/collection_assert_test.go
depends on #1980 
closes #1974 
NOTES:
Unable to get a reliable way to sort by "created" in the core implementation without adding access to `logbook` for the core `Collection`. We would also need to add a `Created` field to `VersionInfo`. If/when we create a `UberData` struct, this field should be moved there. 
Initially, I thought we could rely on the natural ordering of the collection, and assume that each dataset is added to the collection in the order it was created. However, this does not hold for datasets that you pull from a remote, as these can be created at any time & pulled at any later time. However, once we pull a dataset, we have access to it's history & can determine the time of creation via the `logbook`, hence the need to for the core implementation to access `logbook` to …
=> feat(List): order by "name", ascending, and "updated", descending

automation/orchestrator.go, lib/automation.go, lib/http/api.go
Simply exposes a way to get stuff from the run store, which enables cloud to also serve its own.
Part of https://github.com/qri-io/frontend/issues/265
=> feat(lib): run info endpoint

api/util/responses.go, api/util/responses_test.go
Partially revert https://github.com/qri-io/qri/pull/1969. Cloud needs the WritePageResponse. Put it back, with a TODO to remove it once more methods switch over to using cursors for pagination.
=> fix(api): Restore the WritePageResponse method

collection/collection.go
This makes the collection event handler independent of the normal request execution which sometimes caused canceled context due to the event being sent from a go routine attached to a http request.
=> fix(collection): make event handler use independent ctx

docs/go.sum, go.mod, go.sum, transform/startf/ds/dataset.go, transform/startf/ds/dataset_test.go, transform/startf/transform.go
There was a mistake in the spelling of OutputConfig, but this bug was covered up by other bugs in starlib/dataframe. Bump our dependency to fix these bugs, and use the function SetOutputSize instead. Also fix the stack trace display.
=> fix(transform): Bump starlib, fix how OutputConfig is used

transform/staticlark/call_graph_test.go, transform/staticlark/control_flow.go, transform/staticlark/control_flow_test.go, transform/staticlark/dataflow.go, transform/staticlark/dataflow_test.go, transform/staticlark/environment.go, transform/staticlark/functions_test.go, transform/staticlark/testdata/control_funcs.star, transform/staticlark/testdata/some_funcs.star
In dataflow analysis, each branch of an `if` statement is analyzed separately. Then, the environments from those branches are merged together, since assignments from either one can influence bindings. Furthermore, variables in the conditional itself influences the values of assignments within those branches.
First commit adds a `join` field to `if` statements, which indicates where the two branches join up. This make it much easier to recursively analyze each branch of the control structure.
=> feat(transform): Analyze `if` statements by unioning each branch

base/component_status.go, cmd/qri.go, cmd/whatchanged.go, lib/datasets.go, lib/datasets_test.go, lib/http/api.go, lib/lib.go, lib/scope.go, lib/test_runner_test.go
The command `whatchanged` returns what components changed at a specific version of in the history of the dataset.
This command was originally part of FSI, which was removed by commit eaeba31aeb6242bd4aacf79f7c20f9579585d549. However, this command is kind of its own thing, and does not have a hard dependency on FSI functionality. This change adds the command only, without the similar `status` command, which *did* depend on FSI.
=> feat(whatchanged): Restore the `whatchanged` command
